### ISSUE TITLE
WHAT HAPPEN 

### ISSUE THREAD

**Issue by sunset1234321** [bnb-chain/bsc-snapshots#101]
#### System information
geth_windows.exe version
```
Geth
Version: 1.1.7
Git Commit: 74f6b613a4db5cb903f98aca54dbe77d5039ffe8
Architecture: amd64
Go Version: go1.16.10
Operating System: windows
GOPATH=
GOROOT=go
```
OS & Version: Windows10

#### what i run 
`CMD geth_windows.exe --config .\mainnet\config.toml --datadir .\node_real_datadir --diffsync --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0`

#### dir structure 
```
├───node_real_datadir
│   ├───geth
│   │   ├───chaindata
│   │   │   └───ancient
│   │   ├───les.server
│   │   ├───lightchaindata
│   │   ├───nodes
│   │   └───triecache
│   └───keystore
```
#### Expected behaviour
constantly output something in console 

#### Actual behaviour

__stuck__ after console output these 3 lines
```
INFO [01-21|06:27:23.816] Starting Geth on Ethereum mainnet...
INFO [01-21|06:27:23.820] Maximum peer count                       ETH=30 LES=0 total=30
WARN [01-21|06:27:23.823] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
```

**Comment by Gilad-Eisenberger** [comment]
The default `config.toml` has a logging section that forwards logs to a file instead of the console. This is the output when that's set. Consider removing the logging section from the `config.toml` file if you want console output.

**Comment by zigg76** [comment]
can you show the process to setup the node in windows ?
i do it on linux, but i would love to test on windows too.

**Comment by sunset1234321** [comment]
> can you show the process to setup the node in windows ? i do it on linux, but i would love to test on windows too.

sure,  you could telegram me at    @aifebx,   

I later would like to try on linux instead of windows

**Comment by Cryptomooner111** [comment]
Great
