### ISSUE TITLE
Is a full node a requirement to broadcast transactions?

### ISSUE THREAD

**Issue by sunset1234321** [bnb-chain/bsc-snapshots#103]
Sometimes I want to interact with some smart contract ( maybe a decentralized exchange like uni swap)

And I want my transaction to be confirmed the fastest.

But usually, we are relying on other full nodes to help us broadcast the transactions.

For example on uniswap trading website https://app.uniswap.org/#/swap , it use https://mainnet.infura.io/v3/xxxxxxxxxxxxxxxxx as a provider.

But the service is not guaranteed and it could delay your request to broadcast the transactions.

So I am thinking whether building my own node will be better.

What node could broadcast transactions to miners? Is full node the only choice?

**Comment by BrokedTV** [comment]
Infura just give you a quick and easy access, they manage their nodes, otherwise you have to build yours.

**Comment by javimurcia** [comment]
if you are only concerned with your own transactions, maybe a light node is what you need.
