### ISSUE TITLE
解压命令报错

### ISSUE THREAD

**Issue by xdbytes** [bnb-chain/bsc-snapshots#106]
原封不动复制项目中的解压命令，报错。
root@3ape-node:~/data# tar -I lz4 -xvf geth.tar.lz4
tar (child): lz4: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
root@3ape-node:~/data#

**Comment by KyloYang888** [comment]
![image](https://user-images.githubusercontent.com/88371425/153721180-834e56c9-5853-4b06-829f-0533b6feb8eb.png)

Annoying way to compress data.
