### ISSUE TITLE
Is there a Snapshot of BSC Testnet

### ISSUE THREAD

**Issue by netquery** [bnb-chain/bsc-snapshots#108]
Is there a Snapshot of BSC Testnet? Thanks!

**Comment by tibineacsu95** [comment]
I'm really curious about this too. Hopefully someone can shed some light on this. Thank you!

**Comment by wade-liwei** [comment]
me too, 

Is there a Snapshot of BSC Testnet? Thanks!

**Comment by ofarukcaki** [comment]
anyone?

**Comment by echoof** [comment]
me too +1
同求

**Comment by naviocean** [comment]
me too +1

**Comment by let4be** [comment]
is there?

**Comment by folego** [comment]
+1

**Comment by brilliant-lx** [comment]
provided

**Comment by JackPMallon** [comment]
> provided

Where? Looking for the actual bnb data, not eth.
