### ISSUE TITLE
genesis mismatch

### ISSUE THREAD

**Issue by vietthang207** [bnb-chain/bsc-snapshots#112]
After downloading the pruned snapshot, I got this errors:
Fatal: Failed to register the Ethereum service: genesis mismatch: 0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b (leveldb) != 0x0bd5b0537ae3116c904a453c6730fc92b1bed6e12ee8239be2645b7dac4d058b (ancients)

What can be the cause and how can I fixed it? Thanks in advanced!

**Comment by atlaschiew** [comment]
me too !
