### ISSUE TITLE
geth-20220227 file issue

### ISSUE THREAD

**Issue by daron4ever** [bnb-chain/bsc-snapshots#117]
I've downloaded the snapshots from USA and Euro and did a few times and the extraction keeps failing with the following error.
```
tar (child): lz4: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
If I see the process, it seems the file is broken.
<img width="692" alt="Screen Shot 2022-03-01 at 1 53 16 AM" src="https://user-images.githubusercontent.com/18229512/156024480-d281e7c2-cbd6-4ddb-95ab-3d0cb649300b.png">

**Comment by matthewdarwin** [comment]
do you have lz4 installed?

**Comment by heqiang2580** [comment]
您好，我这边也是出现了这个错误，您的弄好了吗，是使用tar解压还是lz4解压的呢。`tar (child): lz4: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now`
