### ISSUE TITLE
Archive Snapshot

### ISSUE THREAD

**Issue by mnguyen-io** [bnb-chain/bsc-snapshots#119]
Hello - are there any archive node snapshots available? I've tried the Erigon version, but ran into frequent crashes resulting data corruption.

**Comment by du5** [comment]
erigon snapshot [BNB48Club/bsc-snapshots](https://github.com/BNB48Club/bsc-snapshots)

**Comment by zzir** [comment]
Is there Geth arvhive snapshot?
