### ISSUE TITLE
we can't query the historical block information

### ISSUE THREAD

**Issue by KyloYang888** [bnb-chain/bsc-snapshots#120]
Hi team. After I run the snapshot with v1.1.8 node, the node is running fine, but we can't query the historical block information. Does anyone know what is the reason for this? Thanks

System information
Geth version: v1.1.8
OS & Version: CentOS

Actual behaviour
```
admin@ip-172-30-34-83:~$ curl --location --request POST 'http://127.0.0.1:8545/'
--header 'Content-Type: application/json'
--data-raw '{
"jsonrpc":"2.0",
"method":"eth_getBlockByNumber",
"params":[
"0x3d0902",
true
],
"id":1
}'
{"jsonrpc":"2.0","id":1,"result":null}
```

**Comment by hundredlee** [comment]
same here
