### ISSUE TITLE
What's the point of Database after ancient prune?

### ISSUE THREAD

**Issue by kawahwookiee** [bnb-chain/bsc-snapshots#128]
It's around 1.1TB.
If I run pruning right after the snapshot is downloaded, 660Gb is freed up immediately:
`INFO [04-19|23:09:26.706] State pruning successful                 pruned=663.39GiB elapsed=9h10m58.273s`

**Comment by jun0tpyrc** [comment]
similar question , want to know "how old " for the data was pruned to remain , i.e.  how much days before the snapshot provided ?
