### ISSUE TITLE
Snapshot size growth in May, 2022

### ISSUE THREAD

**Issue by sonderangebot10** [bnb-chain/bsc-snapshots#131]
Hello,

Could someone please tell me why the snapshot size this month has grown to 1.4TB while last month and before it was about 500GB?

**Comment by blackerhot** [comment]
yes this is gonna be blown up someday. lol This chain is really hard to handle with for a dev side.
1.4 TB ...  this year ... and maybe 5 tb next year ? lol does anyone make some info about this growing ?

**Comment by chenjin-go** [comment]
I feel that the developer has not compressed the snapshot at all

**Comment by MrSonicMaster** [comment]
According to aria2c, it says the DB after ancient data prune is larger than the one without (1528GB vs 1485GB)
![image](https://user-images.githubusercontent.com/19538247/170993220-95d09751-e314-461d-abee-c9918d6a5990.png)

**Comment by 48ClubIan** [comment]
new snapshots release

https://snapshots.bnb48.club/geth.18544401.tar.gz

sha256: d153959220fdeb7d4d7dddd2874c4d06faf2cbc37430add636fb23dc2b2ffde8

!!! db size 512.44 gb, 545.19 gb after decompression

https://github.com/BNB48Club/bsc-snapshots

**Comment by 48ClubIan** [comment]
> 

@sonderangebot10 maybe you would like to check our snapshot service :)

The main factor impacting the size is how the db is pruned.

A completely pruned db may have a decent size while losing the capacity of querying history record.

Necessary trading off.
