### ISSUE TITLE
tar -I lz4 xvf geth.tar.lz4 doesn't works

### ISSUE THREAD

**Issue by mutobui** [bnb-chain/bsc-snapshots#133]
command:
```
tar -I lz4 xvf geth.tar.lz4
```

Environment: ubuntu 20.4

Error:
```
tar: You must specify one of the '-Acdtrux', '--delete' or '--test-label' options
Try 'tar --help' or 'tar --usage' for more information.
```

**Comment by sancag** [comment]
try 

```
tar -I lz4 -xvf geth.tar.lz4
```

let me know if it works as my file seems corrupted.

**Comment by mutobui** [comment]
> tar -I lz4 -xvf geth.tar.lz4

doesn't work either

**Comment by Code0x2** [comment]
tar seems broken for me too, use lz4 instead 
use:
```
sudo apt update && sudo apt install lz4
lz4 -d geth.tar.lz4
```

**Comment by ofarukcaki** [comment]
Also, don't forget to install `liblz4-tool` from apt

**Comment by freaker2k7** [comment]
Works great for me 😁

`wget -q -O - \$(curl -sL "https://raw.githubusercontent.com/binance-chain/bsc-snapshots/main/README.md" | grep 'https://download' | head -n1 | tr -d ']' | tr -d '(') | tar -I lz4 --overwrite -xf -`
