### ISSUE TITLE
can not extract current snap geth-20220525.tar.lz4 ?

### ISSUE THREAD

**Issue by MhaiRuMhaiShee** [bnb-chain/bsc-snapshots#134]
anyone face same issue ?

**Comment by blackerhot** [comment]
x server/data-seed/geth/
x server/data-seed/geth/LOCK
x server/data-seed/geth/lightchaindata/
x server/data-seed/geth/lightchaindata/LOCK
x server/data-seed/geth/lightchaindata/LOG
x server/data-seed/geth/lightchaindata/MANIFEST-000000
x server/data-seed/geth/lightchaindata/CURRENT
x server/data-seed/geth/lightchaindata/000001.log
x server/data-seed/geth/les.server/
x server/data-seed/geth/les.server/LOCK
x server/data-seed/geth/les.server/LOG
x server/data-seed/geth/les.server/CURRENT
x server/data-seed/geth/les.server/CURRENT.bak
x server/data-seed/geth/les.server/000414.ldb
x server/data-seed/geth/les.server/000415.log
x server/data-seed/geth/les.server/MANIFEST-000416
x server/data-seed/geth/les.server/000417.ldb
x server/data-seed/geth/nohup.out
x server/data-seed/geth/triecache/
x server/data-seed/geth/triecache/metadata.bin
x server/data-seed/geth/triecache/data.7.bin           <<<<<<<<<< stuck here

**Comment by anton-hniadyi** [comment]
The same issue with current snapshot. Did you solve it? @blackerhot
