### ISSUE TITLE
Can I use the existing node to change to Archive mode?

### ISSUE THREAD

**Issue by pinswap** [bnb-chain/bsc-snapshots#136]
The query data requires the node to be in Archive mode, but the nodes that have been synchronized are in full mode by default. Is it possible to start an existing node as archive? Or do you want to re-synchronize the new node data in Archive mode?
What should I do now?

**Comment by AlgoTradingExpert** [comment]
you can make the node Archive as well from the current block by changing it's start command. You can start the node with this following changes
 --syncmode=full --gcmode "archive" --snapshot=false
 
After restarting the node if you want to make it archive from some specific block then you can use the debug.setHead('0x...') to start it from the specific block.
