### ISSUE TITLE
snapshot file is incomplete

### ISSUE THREAD

**Issue by BabySid** [bnb-chain/bsc-snapshots#152]
Hi, i cannot getBlock before number 18817620
version:  geth v1.1.11

i sync from the snap below:
![图片](https://user-images.githubusercontent.com/6658943/176883156-9c5175ac-cac9-4b98-817a-9dfea01be189.png)

and now, geth have synced to the latest block.

the problem is why i cannot get hisotry block

```
> eth.getBlockByNumber(18817620)
null
> eth.getBlockByNumber(18817621)
{
  difficulty: "0x2",
  ……
```

Thanks.

**Comment by atlaschiew** [comment]
after long efforts downloaded geth-20220705.tar.lz4, unfortunately i encounter genesis mismatch error

Fatal: Failed to register the Ethereum service: genesis mismatch: 0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b (leveldb) != 0xc21c6829af2b8655f8961b3e26018e53846aaad1ec936c505fe5b7cedb5a9e44 (ancients)

please help :(
