### ISSUE TITLE
Head state missing, repairing  geth-20220703.tar.lz4

### ISSUE THREAD

**Issue by greyireland** [bnb-chain/bsc-snapshots#154]
t=2022-07-04T11:57:20+0000 lvl=warn msg="Head state missing, repairing"       number=19,182,191 hash=0x337ea854e565e2b544452239b0055895cd33dde2171e9275b44cfd3e0dabfca3 snaproot=0xecdb3384f7a5ac6420a26878156bd66948c7f52e12ca7ddf04dd5f7a74671f78

**Comment by iakisme** [comment]
fixed
