### ISSUE TITLE
genesis mismatch

### ISSUE THREAD

**Issue by atlaschiew** [bnb-chain/bsc-snapshots#155]
after long efforts downloaded geth-20220705.tar.lz4, unfortunately i encounter genesis mismatch error

Fatal: Failed to register the Ethereum service: genesis mismatch: 0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b (leveldb) != 0xc21c6829af2b8655f8961b3e26018e53846aaad1ec936c505fe5b7cedb5a9e44 (ancients)

please help :(

**Comment by atlaschiew** [comment]
ok, i manage to solve it by running latest version of geth ..thanks guy

**Comment by arthurwolf** [comment]
I have the same issue, but using the latest version of geth didn't solve it. Anyone has an idea?

**Comment by arthurwolf** [comment]
Fatal: Failed to register the Ethereum service: genesis mismatch: 0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b (leveldb) != 0xc21c6829af2b8655f8961b3e26018e53846aaad1ec936c505fe5b7cedb5a9e44 (ancients)
