### ISSUE TITLE
Snapshot is not complete

### ISSUE THREAD

**Issue by northmz** [bnb-chain/bsc-snapshots#163]
I have downloaded the snapshot and synced my server as full node, but first blocks (up to block 10M) don't exist and I just have information of recent blocks. Where can I find a full snapshot?

**Comment by technologiespro** [comment]
+

**Comment by technologiespro** [comment]
> I have downloaded the snapshot and synced my server as full node, but first blocks (up to block 10M) don't exist and I just have information of recent blocks. Where can I find a full snapshot?

a snapshot from the community helped me now everything is fine https://github.com/BNB48Club/bsc-snapshots#geth-snapshots

**Comment by daron4ever** [comment]
I have the same issue. I tried many times, but it synced from 0 block with recent snapshots.
