### ISSUE TITLE
Do we have full snapshot?

### ISSUE THREAD

**Issue by appop** [bnb-chain/bsc-snapshots#168]
Do we have full snapshot?

We want to sync our own full BSC node, but we can't download any full snapshot for BSC.

**Comment by manefesto** [comment]
@appop you have error like that? :
` wget -c https://download.bsc-snapshot.workers.dev/geth-20220828.tar.lz4
--2022-08-30 11:40:59--  https://download.bsc-snapshot.workers.dev/geth-20220828.tar.lz4
Resolving download.bsc-snapshot.workers.dev (download.bsc-snapshot.workers.dev)... 188.114.97.2, 188.114.96.2, 2a06:98c1:3121::2, ...
Connecting to download.bsc-snapshot.workers.dev (download.bsc-snapshot.workers.dev)|188.114.97.2|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2022-08-30 11:40:59 ERROR 500: Internal Server Error.`

**Comment by kaolula** [comment]
my error like this.how to solve it?
