### ISSUE TITLE
Latest snapshot is corrupt

### ISSUE THREAD

**Issue by MrSonicMaster** [bnb-chain/bsc-snapshots#178]
Latest snapshot posted is not complete. seen prev with same concern - nohup.out in server/data-seed/geth folder spams issues about out of space:
```
cp: failed to extend ‘/server/data-seed/geth/chaindata/24367886.ldb’: No space left on device
cp: cannot create regular file ‘/server/data-seed/geth/chaindata/24337054.ldb’: No space left on device
cp: cannot create regular file ‘/server/data-seed/geth/chaindata/24282339.ldb’: No space left on device
cp: cannot create regular file ‘/server/data-seed/geth/chaindata/24425900.ldb’: No space left on device
cp: cannot create regular file ‘/server/data-seed/geth/chaindata/24293883.ldb’: No space left on device
cp: cannot create regular file ‘/server/data-seed/geth/chaindata/24599339.ldb’: No space left on device
```

and on extract/run geth with snapshot, I get this:
```
t=2022-10-02T09:57:27-0400 lvl=info msg="Loaded most recent local header"  number=21,785,708 hash=0x8302626e0c28dda5188a0bdf887a8c3376f289892f96df058a4f3ad114adb2fe td=43,327,011 age=1d21h13m
t=2022-10-02T09:57:27-0400 lvl=info msg="Loaded most recent local full block" number=21,785,708 hash=0x8302626e0c28dda5188a0bdf887a8c3376f289892f96df058a4f3ad114adb2fe td=43,327,011 age=1d21h13m
t=2022-10-02T09:57:27-0400 lvl=info msg="Loaded most recent local fast block" number=21,785,708 hash=0x8302626e0c28dda5188a0bdf887a8c3376f289892f96df058a4f3ad114adb2fe td=43,327,011 age=1d21h13m
t=2022-10-02T09:57:27-0400 lvl=info msg="Loaded last fast-sync pivot marker"  number=6,920,578
t=2022-10-02T09:57:27-0400 lvl=warn msg="Head state missing, repairing"       number=21,785,708 hash=0x8302626e0c28dda5188a0bdf887a8c3376f289892f96df058a4f3ad114adb2fe snaproot=0xadae28edf4344de03a2096745d
93b61b4116c3ba1ae8c6ff996a00c4d1c6fdac
```

(from link https://download.bsc-snapshot.workers.dev/geth-20220930.tar.lz4)

**Comment by MrSonicMaster** [comment]
Also seems curious that snaphot is so large even if it is meant to be after Ancient Data Prune. Node makes logs about ancient dir containing 21 mil blocks:

```
t=2022-10-02T09:57:25-0400 lvl=info msg="Allocated trie memory caches" clean="1.17 GiB" dirty="1.95 GiB"
t=2022-10-02T09:57:25-0400 lvl=info msg="Allocated cache and file handles" database=/home/mrsonic/server/data-seed/geth/chaindata cache="3.12 GiB" handles=524,288
t=2022-10-02T09:57:26-0400 lvl=info msg="AncientDB item count"             items=21,695,709
t=2022-10-02T09:57:26-0400 lvl=info msg="Opened ancient database"          database=/home/mrsonic/server/data-seed/geth/chaindata/ancient readonly=false frozen=21,695,709
t=2022-10-02T09:57:26-0400 lvl=info msg="Initialised chain configuration"  config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Peters
burg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, CatalystBlock: <nil>, London: <nil>, ArrowGlacier: <nil>, MergeFork:<nil>,
 Euler: 18907621, Gibbs: <nil>, Engine: parlia}"
t=2022-10-02T09:57:27-0400 lvl=info msg="Unprotected transactions allowed"
t=2022-10-02T09:57:27-0400 lvl=info msg="Initialising Ethereum protocol"   network=56 dbversion=8
```

Did db get mixed up somehow?

I would use BNB48club snapshot, but their db gets completely corrupted and irrecoverable on first time where node gets force shut down. I think MPT state is possibly needed to assist with such recovery, or maybe there is bug in current Fast Node for when it gets force shut down. I did not have issues on prev db versions posted here which had MPT state included.

**Comment by MrSonicMaster** [comment]
And just for completeness, I just calculated md5 hash of the archive I downloaded. It is full match:

```
mrsonic@mrsonic:/media/mrsonic/Storage$ md5sum geth.tar.lz4 
e81283745a5f4a905614cce7274d766b  geth.tar.lz4
mrsonic@mrsonic:/media/mrsonic/Storage$ 
```

**Comment by Interventionist** [comment]
Same here, I downloaded the whole snapshot a few times, and I always get "Head state missing, repairing" error.

**Comment by MrSonicMaster** [comment]
> Same here, I downloaded the whole snapshot a few times, and I always get "Head state missing, repairing" error.

Which one did you download? from block 20220930 or the newest one posted just 6 hours ago from block 20221002? I'm downloading the newest one now and hoping they've fixed it, but will cancel if you say the newest one is still yet corrupt.

**Comment by MrSonicMaster** [comment]
Update: can confirm even latest snapshot is corrupt with same issue (logs are from very first startup after very latest snapshot finished extracting):

```
t=2022-10-02T23:25:24-0400 lvl=info msg="Set global gas cap" cap=50,000,000
t=2022-10-02T23:25:24-0400 lvl=info msg="Allocated trie memory caches" clean="1.17 GiB" dirty="1.95 GiB"
t=2022-10-02T23:25:24-0400 lvl=info msg="Allocated cache and file handles" database=/home/mrsonic/server/data-seed/geth/chaindata cache="3.12 GiB" handles=524,288
t=2022-10-02T23:25:26-0400 lvl=info msg="AncientDB item count"             items=21,747,561
t=2022-10-02T23:25:26-0400 lvl=info msg="Opened ancient database"          database=/home/mrsonic/server/data-seed/geth/chaindata/ancient readonly=false frozen=21,747,561
t=2022-10-02T23:25:26-0400 lvl=info msg="Initialised chain configuration"  config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, CatalystBlock: <nil>, London: <nil>, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: <nil>, Engine: parlia}"
t=2022-10-02T23:25:26-0400 lvl=info msg="Deep froze chain segment"         blocks=18 elapsed=25.901ms number=21,747,578 hash=0xd7450645bc03be9aa399cdb3c57e06facd00992c3973936b7d899c9d88cd2ff8
t=2022-10-02T23:25:27-0400 lvl=info msg="Unprotected transactions allowed"
t=2022-10-02T23:25:27-0400 lvl=info msg="Initialising Ethereum protocol"   network=56 dbversion=8
t=2022-10-02T23:25:27-0400 lvl=info msg="Loaded most recent local header"  number=21,837,578 hash=0xf8419ff4dbb951ddb92cb2d7ddcd87b76653666d1e0cc428da9ece33b0eede74 td=43,430,225 age=15h11m28s
t=2022-10-02T23:25:27-0400 lvl=info msg="Loaded most recent local full block" number=21,837,578 hash=0xf8419ff4dbb951ddb92cb2d7ddcd87b76653666d1e0cc428da9ece33b0eede74 td=43,430,225 age=15h11m28s
t=2022-10-02T23:25:27-0400 lvl=info msg="Loaded most recent local fast block" number=21,837,578 hash=0xf8419ff4dbb951ddb92cb2d7ddcd87b76653666d1e0cc428da9ece33b0eede74 td=43,430,225 age=15h11m28s
t=2022-10-02T23:25:27-0400 lvl=info msg="Loaded last fast-sync pivot marker"  number=6,920,578
t=2022-10-02T23:25:27-0400 lvl=warn msg="Head state missing, repairing"       number=21,837,578 hash=0xf8419ff4dbb951ddb92cb2d7ddcd87b76653666d1e0cc428da9ece33b0eede74 snaproot=0xac4f675b00a7747c0fd630b391420414862d8c72751946dc61e039094a8c5bdc
```

**Comment by Interventionist** [comment]
> > Same here, I downloaded the whole snapshot a few times, and I always get "Head state missing, repairing" error.
> 
> Which one did you download? from block 20220930 or the newest one posted just 6 hours ago from block 20221002? I'm downloading the newest one now and hoping they've fixed it, but will cancel if you say the newest one is still yet corrupt.

The 20220930 version. After 3 hours it started syncing, and it took less than 1 hour to finish sync (seems fast). But now, when I try to interract with the node, I get errors, and the CPU usage for geth is anormally low (below 10%). I don't know if it's because of a corruption.

**Comment by MrSonicMaster** [comment]
> The 20220930 version. After 3 hours it started syncing, and it took less than 1 hour to finish sync (seems fast). But now, when I try to interract with the node, I get errors, and the CPU usage for geth is anormally low (below 10%). I don't know if it's because of a corruption.

Decided to just snap sync from scratch this morning, will probably be a cleaner db anyways. 10% finished with state sync, maybe 1-2 days left till finished with sync+heal.

**Comment by cyhhao** [comment]
Yeah, same problem.
geth-20220919.tar.lz4  830G is fine ✅
All versions after it are broken
geth-20221002.tar.lz4  1.2T  Incorrect ❌

**Comment by MrSonicMaster** [comment]
> Yeah, same problem.

I suggest snap sync yourself from scratch. Started yesterday morning, already finished state sync up to head and am onto state heal now. One more day and will likely be done.

**Comment by maxisacoder** [comment]
same here

**Comment by MrSonicMaster** [comment]
> Could you share your setup and start command? I am not sure about using `--diffsyc` flags? Did u leverage the `tries-verify-mode` ?

No, I did not use tries-verify-mode because - without MPT state current fast-node architecture can not recover from crash. However it would dramatically increase sync time, probably to <1 day if you can do without it. I believe diffsync and snapsync are mutually exclusive, latter is for initial sync and former an alternative for full sync for staying up to date with head. I believe diffsync decreases your local computation requirement at cost of increased latency (must wait for other to process full block and send you the the diff layer.) Heal stage takes a long time, and will only get longer if you shut node down any time during sync or have slow IOPS. current bsc-geth code is also missing bug fixes for snapsync from upstream geth repo, I merged those in my copy.

> bnb48club snapshot is smaller and works good, I didn’t have any problem with it

This is why I can't use their snapshot ^

**Comment by MrSonicMaster** [comment]
Assuming newer snapshots are fixed

**Comment by mas1337** [comment]
Same here, latest snapshot is corrupt.

**Comment by kaber2** [comment]
Wasted 10TB for downloading corrupt snapshots. Seriously BSC guys, can you do *anything* right?

**Comment by Jolly23** [comment]
> No, I did not use tries-verify-mode because - without MPT state current fast-node architecture can not recover from crash. However it would dramatically decrease sync time, probably to <1 day if you can do without it. I believe diffsync and snapsync are mutually exclusive, latter is for initial sync and former an alternative for full sync for staying up to date with head. I believe diffsync decreases your local computation requirement at cost of increased latency (must wait for other to process full block and send you the diff layer.) Snap sync trie heal stage takes a longest time by far, and will only get longer if you shut node down any time during sync or have slow IOPS. current bsc-geth code is also missing bug fixes for snapsync from upstream geth repo, I merged those in my copy. Though, It is worth noting that I underestimated how long it will take. I am still in state heal, couple hundred million trie nodes healed but may still be many left!

Hello @MrSonicMaster , are you using Geth flag --snapshot=false ? Could you please share some understandings and suggestions about --snapshot flag we using with Geth?

**Comment by MrSonicMaster** [comment]
> > No, I did not use tries-verify-mode because - without MPT state current fast-node architecture can not recover from crash. However it would dramatically decrease sync time, probably to <1 day if you can do without it. I believe diffsync and snapsync are mutually exclusive, latter is for initial sync and former an alternative for full sync for staying up to date with head. I believe diffsync decreases your local computation requirement at cost of increased latency (must wait for other to process full block and send you the diff layer.) Snap sync trie heal stage takes a longest time by far, and will only get longer if you shut node down any time during sync or have slow IOPS. current bsc-geth code is also missing bug fixes for snapsync from upstream geth repo, I merged those in my copy. Though, It is worth noting that I underestimated how long it will take. I am still in state heal, couple hundred million trie nodes healed but may still be many left!
> 
> Hello @MrSonicMaster , are you using Geth flag --snapshot=false ? Could you please share some understandings and suggestions about --snapshot flag we using with Geth?

snapshot is an acceleration structure which duplicates latest chain data in flat key-value mapping, which is an order of magnitude faster for reads/lookups than reading from MPT state. it is suggested to use --snapshot=true (the default).
