### ISSUE TITLE
 lvl=warn msg="Head state missing, repairing"       number=21,997,828 

### ISSUE THREAD

**Issue by GuolongCyber** [bnb-chain/bsc-snapshots#181]
t=2022-10-09T20:03:12+0800 lvl=warn msg="Head state missing, repairing"       number=21,997,828 hash=0xe7468fe47108418d4245b5e480ae540b6d3230462e10941f4eb8cfd0d6e5e1f4

[geth-20221008.tar.lz4](https://download.bsc-snapshot.workers.dev/geth-20221008.tar.lz4)

**Comment by NearZXH** [comment]
they changed the package, see [the commit]( https://github.com/bnb-chain/bsc-snapshots/commit/570a574165c712a6bcb32dc18de9505fbda9a54e)

**Comment by NearZXH** [comment]
you may need to download the package again if you dowwnloaded it yesterday

**Comment by GuolongCyber** [comment]
@NearZXH 

> you may need to download the package again if you dowwnloaded it yesterday，or use the [bnb48club](https://github.com/BNB48Club/bsc-snapshots) snapshots.

@NearZXH  Yes, I did. I downloaded the changed package again, and it remains the same issue.

**Comment by NearZXH** [comment]
> 

check the md5, in my case, it's equal to the value `be1e2ffbfc9101288f8b2a89ccb29f43` but not `b13100633bfdcddffdd8304994a2b1be` just like [the commit](https://github.com/bnb-chain/bsc-snapshots/commit/570a574165c712a6bcb32dc18de9505fbda9a54e) . I just trying to use the [bnb48club](https://github.com/BNB48Club/bsc-snapshots) version.

**Comment by NearZXH** [comment]
similar issue: [178](https://github.com/bnb-chain/bsc-snapshots/issues/178) & [180](https://github.com/bnb-chain/bsc-snapshots/issues/180)

**Comment by GuolongCyber** [comment]
> similar issue: [178](https://github.com/bnb-chain/bsc-snapshots/issues/178) & [180](https://github.com/bnb-chain/bsc-snapshots/issues/180)

@NearZXH  Yes, super waste of time...

**Comment by GuolongCyber** [comment]
@NearZXH  我最后使用了 [bnb48club](https://github.com/BNB48Club/bsc-snapshots) 官方那个snapshot还是有问题。不过bnb48club的快照是不包含MPT数据的， 访问远古数据会出现缓慢，出块停止然后恢复并一次性把所有停止的块一次性同步过来。 这可能是一个弊端，不过我倒是可以接受，毕竟占用存储空间小很多,只有300GB

**Comment by GuolongCyber** [comment]
> @NearZXH 我最后使用了 [bnb48club](https://github.com/BNB48Club/bsc-snapshots) 官方那个snapshot还是有问题。不过bnb48club的快照是不包含MPT数据的， 访问远古数据会出现缓慢，出块停止然后恢复并一次性把所有停止的块一次性同步过来。 这可能是一个弊端，不过我倒是可以接受，毕竟占用存储空间小很多,只有300GB

官方的 snapshot  出现 `Head state missing, repairing`，大概等了3-4个小时，修复完成。  然后同步出现问题，同步速度很慢，追不上最新，不知道什么问题，同步了一晚上 也没有完成。

**Comment by nbenyahia** [comment]
Same issue here ! Only snapshot of the 20220919 works fine but the link has been deleted. @iakisme

**Comment by GuolongCyber** [comment]
> Same issue here ! Only snapshot of the 20220919 works fine but the link has been deleted. @iakisme 

After two days of trying, I gave up. I just used bnb48club's snapshot for now.

**Comment by echoof** [comment]
> > @NearZXH 我最后使用了 [bnb48club](https://github.com/BNB48Club/bsc-snapshots) 官方那个snapshot还是有问题。不过bnb48club的快照是不包含MPT数据的， 访问远古数据会出现缓慢，出块停止然后恢复并一次性把所有停止的块一次性同步过来。 这可能是一个弊端，不过我倒是可以接受，毕竟占用存储空间小很多,只有300GB
> 
> 官方的 snapshot 出现 `Head state missing, repairing`，大概等了3-4个小时，修复完成。 然后同步出现问题，同步速度很慢，追不上最新，不知道什么问题，同步了一晚上 也没有完成。

同样的问题

**Comment by kaolula** [comment]
I have the same problem

- log
```t=2022-10-13T03:10:33+0000 lvl=warn msg="Head state missing, repairing"       number=22,054,838 hash=0xff8e94a263b0dd479c255e8679c37cff3e0732eed9bb8c5e48a377c7057a7b8f snaproot=0xdff2167645890b72a8e909748ca04a984b45eb400906fb8ff70693bc8a83ce25```

**Comment by flopell** [comment]
> Same issue here ! Only snapshot of the 20220919 works fine but the link has been deleted. @iakisme

It's still available for download. You can use this command :

`aria2c -o geth.tar.lz4 -s14 -x14 -k100M https://download.bsc-snapshot.workers.dev/geth-20220919.tar.lz4 -o geth.tar.lz4`
