### ISSUE TITLE
can't synchronize with latest release and snapshot

### ISSUE THREAD

**Issue by muczos** [bnb-chain/bsc-snapshots#182]
Hi, 

since few days I'm trying to get my own instance of bsc node. 
I've installed latest geth - 1.1.15-f3fd0f8b and downloaded latest snapshot https://snapshots.bnb48.club/geth.21943608.tar.lz4 
I've used config provided with 1.1.15-f3fd0f8b release (mainnet) and run geth with options recommended here https://github.com/BNB48Club/bsc-snapshots, which was:
`--txlookuplimit=0 --diffsync=true --syncmode=full --tries-verify-mode=none --pruneancient=true --diffblock=5000`

Unfortunatelly I'm not able to sync, Since three days the only thing I'm seeing in logs is:
`lvl=warn msg="Synchronisation failed, retrying"      err="peer is unknown or unhealthy"`

Before that I didn't have problem with peers, but couldn't sync anyway. I've tried to tune configuration increasing MaxPeers and Cache, also experiment with other settings I've found searching accross issues in github. No luck.

My hardware configuration should be sufficient, bare metal 16 cores, 64 GB RAM, fast nvme drive. Server is located in Hetzner/Germany, network is really good.

Am I missing something? Does the StaticNodes list provided with latest release is wrong somehow?

**Comment by Paulius0112** [comment]
I face the same issue. Have you tried upgrading your node to v1.1.16?

**Comment by edjiH** [comment]
Did you manage to make it work ? I have the same issue running with v1.1.16 and hardware config more than sufficient

**Comment by echoof** [comment]
Wait more,  may succeed
