### ISSUE TITLE
Download error erigon snapshot: erigon-20220806.tar.lz4

### ISSUE THREAD

**Issue by antoni7654** [bnb-chain/bsc-snapshots#186]
Hi:

I've been trying to download all day long the Erigon snapshot: https://download.bsc-snapshot.workers.dev/snapshot/erigon-20220806.tar.lz4 and keeps replying Error 500. I had downloaded some of this file yesterday until this error happened:

wget -c -O erigon.tar.lz4  https://download.bsc-snapshot.workers.dev/snapshot/erigon-20220806.tar.lz4
--2022-10-17 22:34:48--  https://download.bsc-snapshot.workers.dev/snapshot/erigon-20220806.tar.lz4
Resolving download.bsc-snapshot.workers.dev (download.bsc-snapshot.workers.dev)... 172.67.219.254, 104.21.70.50, 2606:4700:3034::ac43:dbfe, ...
Connecting to download.bsc-snapshot.workers.dev (download.bsc-snapshot.workers.dev)|172.67.219.254|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2022-10-17 22:34:48 ERROR 500: Internal Server Error.

Thanks.

**Comment by AgostinhoBarbosa** [comment]
I'm having the same problem, how to work around it?

**Comment by antoni7654** [comment]
> I'm having the same problem, how to work around it?

You can use the snapshot from here:  https://github.com/BNB48Club/bsc-snapshots   It worked for me. Regards

**Comment by AgostinhoBarbosa** [comment]
Thanks, I'm downloading it to test
