### ISSUE TITLE
Canonical hash missing, can't freeze     number=19,594,091

### ISSUE THREAD

**Issue by bdonglobal** [bnb-chain/bsc-snapshots#190]
I downloaded the https://pub-10cd0733ed3540f1a5bd893cdcaf4027.r2.dev/geth-20221101-not-fastnode.tar.lz4, and Geth client 1.1.16, when start to sync with archive mode, it shows the following, what does this mean and how to resolve it ?

ERROR[11-06|02:28:00.878] Canonical hash missing, can't freeze     number=19,594,091
ERROR[11-06|02:28:00.878] Canonical hash missing, can't freeze     number=19,594,092
ERROR[11-06|02:28:00.878] Canonical hash missing, can't freeze     number=19,594,093
ERROR[11-06|02:28:00.878] Canonical hash missing, can't freeze     number=19,594,094
ERROR[11-06|02:28:00.878] Canonical hash missing, can't freeze     number=19,594,095
ERROR[11-06|02:28:00.878] Canonical hash missing, can't freeze     number=19,594,096
ERROR[11-06|02:28:00.878] Canonical hash missing, can't freeze     number=19,594,097
ERROR[11-06|02:28:00.878] Canonical hash missing, can't freeze     number=19,594,098
ERROR[11-06|02:28:00.878] Canonical hash missing, can't freeze     number=19,594,099
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,100
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,101
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,102
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,103
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,104
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,105
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,106
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,107
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,108
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,109
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,110
ERROR[11-06|02:28:00.879] Canonical hash missing, can't freeze     number=19,594,111
INFO [11-06|02:28:01.198] Deep froze chain segment                 blocks=30001 elapsed=1.661s    number=19,594,111

**Comment by bdonglobal** [comment]
Update the steps and the output, after I wait for 1 day, I hit another issue:

ERROR[11-07|01:16:07.238] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:17:07.238] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:18:07.239] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:19:07.239] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:20:07.239] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:21:07.240] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:22:07.241] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:23:07.242] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:24:07.243] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:25:07.243] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:26:07.244] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:27:07.245] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:28:07.246] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:29:07.246] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:30:07.247] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:31:07.247] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:32:07.248] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:33:07.249] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:34:07.249] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:35:07.250] Current full block number unavailable    hash=dd2db4..6363fb
ERROR[11-07|01:36:07.250] Current full block number unavailable    hash=dd2db4..6363fb

my script is ,

./geth_linux --datadir `pwd`/data --datadir.ancient `pwd`/ancient --networkid 56 --syncmode full --gcmode archive --cache 16092 --txpool.globalslots 50000 --allow-insecure-unlock  --http --http.addr "0.0.0.0" --http.port 7000 --maxpeers 100 --http.api "eth,net,web3,admin,debug,personal,txpool"  --txpool.globalqueue 50000 --txpool.lifetime 5h0m0s  --ws --ws.addr "0.0.0.0" --ws.api "txpool,personal,admin,eth,net,web3"  --ws.origins "*" --snapshot=true --triesInMemory 2000 --bootnodes "enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311,enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@34.246.65.14:30311"  --diffsync --txlookuplimit=0 --nocompaction --tries-verify-mode=none --pruneancient=true --diffblock=5000

**Comment by isaacyuno** [comment]
You are using --gcmode archive and --pruneancient=true together, this will not work.
