### ISSUE TITLE
latest geth & snapshots Not working

### ISSUE THREAD

**Issue by sangbeomji89** [bnb-chain/bsc-snapshots#191]
I have problem on running geth with snapshot.

Environment)
geth : 1.1.17
snapshot : [geth-20221101-not-fastnode.tar.lz4](https://pub-10cd0733ed3540f1a5bd893cdcaf4027.r2.dev/geth-20221101-not-fastnode.tar.lz4)

geth-cmd : 
nohup geth --config /conf/config.toml --datadir /ldata/049 --diffsync --cache 8000 --port 20493 --ws --ws.port=20492 --ws.addr=0.0.0.0 --ws.origins='*' --rpc.allow-unprotected-txs --txlookuplimit 0 1>/dev/null 2>&1 &

I just followed the readme on "https://github.com/bnb-chain/bsc-snapshots"

But the log like below and then finally the geth process is killed.

[LOGS]
t=2022-11-06T07:13:43+0000 lvl=info msg="Set global gas cap" cap=50,000,000
t=2022-11-06T07:13:43+0000 lvl=info msg="Allocated trie memory caches" clean="1.17 GiB" dirty="1.95 GiB"
t=2022-11-06T07:13:43+0000 lvl=info msg="Allocated cache and file handles" database=/ldata/049/geth/chaindata cache="3.12 GiB" handles=32767
t=2022-11-06T07:13:46+0000 lvl=info msg="AncientDB item count"             items=3,443,110
t=2022-11-06T07:13:46+0000 lvl=info msg="Opened ancient database"          database=/ldata/049/geth/chaindata/ancient readonly=false frozen=22,587,207
t=2022-11-06T07:13:46+0000 lvl=info msg="Initialised chain configuration"  config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, CatalystBlock: <nil>, London: <nil>, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: <nil>, Nano: 21962149, Moran: 22107423, Engine: parlia}"
t=2022-11-06T07:14:01+0000 lvl=info msg="Unprotected transactions allowed"
t=2022-11-06T07:14:01+0000 lvl=info msg="Initialising Ethereum protocol"   network=56 dbversion=8

**Comment by isaacyuno** [comment]
Hi, please try the latest snapshot again and see how it goes. But usually geth should not quit unexpectly
