### ISSUE TITLE
why no pruning?

### ISSUE THREAD

**Issue by sonderangebot10** [bnb-chain/bsc-snapshots#192]
Hello,

When can we expect for the next prune of the snapshot to happen? Currently the latest snapshot is 1.7TB in size which is becoming a bit too big.

**Comment by 0x090909** [comment]
Im having same problem

**Comment by gaiyaa** [comment]
Im having same problem

**Comment by du5** [comment]
https://github.com/BNB48Club/bsc-snapshots

**Comment by sonderangebot10** [comment]
BNB48 snapshot requires `--tries-verify-mode=none` which is not good for my use case

**Comment by du5** [comment]
In the near future we may release local snapshots :)

**Comment by wangtsiao** [comment]
same probelm

**Comment by tiendo1011** [comment]
same problem + 1

**Comment by du5** [comment]
Full node is generated with --tries-verify-mode=local

https://github.com/48Club/bsc-snapshots#full-node
