### ISSUE TITLE
Last snapshot non working :) 

### ISSUE THREAD

**Issue by karanod** [bnb-chain/bsc-snapshots#193]

**Comment by kris-ss** [comment]
Hello, the issue with the latest snapshot has been escalated to the team. 
Please use the geth-20221116.tar.lz4 snapshot for now. 

You can also consider the snapshot from BNB48Club - https://github.com/BNB48Club/bsc-snapshots. The snapshot doesn't have MPT data though and it is pruned (with only latest 90000 block, ~around 3 days). If you are not building a validator node and you don't need > ~3 days block data, it should work for you.
