### ISSUE TITLE
internal server error 500 for newest snapshot

### ISSUE THREAD

**Issue by Aracki** [bnb-chain/bsc-snapshots#195]
When downloading latest snapshot https://download.bsc-snapshot.workers.dev/geth-20221128.tar.lz4, we are getting 500.

**Comment by kris-ss** [comment]
Hello, you can try with below script

aria2c -o geth.tar.lz4 -s14 -x14 -k100M https://download.bsc-snapshot.workers.dev/geth-20221128.tar.lz4 -o geth.tar.lz4

**Comment by Aracki** [comment]
Thanks for the suggestion!
