### ISSUE TITLE
erigon snapshot lz4 file corrupted

### ISSUE THREAD

**Issue by justforfunya** [bnb-chain/bsc-snapshots#199]
after downloading the  https://download.bsc-snapshot.workers.dev/erigon-data-20221222.tar.lz4 file 
untar command says Decompression error : ERROR_decompressionFailed
I think the erigon-data-20221222.tar.lz4 is corrupted

`root@node:/home/x# ls -al  erigon_bsc.tar.lz4
-rw-r--r-- 1 root root 2777507284558 12月 27 01:41 erigon_bsc.tar.lz4
root@node:/home/x#  lz4 -t erigon_bsc.tar.lz4

Decompressed : 28088 MB  Error 66 : Decompression error : ERROR_decompressionFailed`

**Comment by calmbeing** [comment]
@justforfunya Can you try to use wget instead of aria2c? Then try to tar again, I think there's a broken issue occur while using aria2c to download files
`wget https://download.bsc-snapshot.workers.dev/erigon-data-20221222.tar.lz4`

**Comment by calmbeing** [comment]
@justforfunya Try this latest snapshot please: `https://download.bsc-snapshot.workers.dev/erigon-data-20221227.tar.lz4`
