### ISSUE TITLE
The snapshot is almost 1.9T

### ISSUE THREAD

**Issue by syaringan357** [bnb-chain/bsc-snapshots#200]
The snapshot is almost 1.9T, and my disk is only 2T. After removing some system files, the download cannot be completed at all. Can you prune and compress it?

**Comment by matthewdarwin** [comment]
Please get a bigger disk.

**Comment by du5** [comment]
Full node is generated with --tries-verify-mode=local

https://github.com/48Club/bsc-snapshots#full-node
