### ISSUE TITLE
no erigon snapshot checksum

### ISSUE THREAD

**Issue by khanghh** [bnb-chain/bsc-snapshots#205]
Could you provide the md5 or sha1 checksum of the erigon snapshot lz4 file?
Some people (included me) got issues when downloading the snapshot. 
Looks like your sever not supported resuming the download and it is out of bandwidth.
I downloaded many times and got the mdbx database of erigon corrupted during sync stage.
#199 
#203

**Comment by kris-ss** [comment]
Thanks for the feedback. We've informed the team about this and they will add it.
