### ISSUE TITLE
erigon_data_20230109.tar.lz4 not working(MDBX_CORRUPTED)

### ISSUE THREAD

**Issue by justforfunya** [bnb-chain/bsc-snapshots#206]
after downloaded the whole file ,unztar says error:

 tar -I lz4 -xvf erigon_data_20230109.tar.lz4
tar: Removing leading `/' from member names
/server1/home/qa/eri/erigon/data/chaindata/mdbx.dat
Error 68 : Unfinished stream
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

run erigon says:
EROR[01-11|20:09:45.279] Erigon startup                           err="mdbx_env_open: MDBX_CORRUPTED: Maybe free space is over on disk. Otherwise it's hardware failure. Before creating issue please use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk. To handle hardware risks: use ECC RAM, use RAID of disks, run multiple application instances (or do backups). If hardware checks passed - check FS settings - 'fsync' and 'flock' must be enabled.  Otherwise - please create issue in Application repo. On default DURABLE mode, power outage can't cause this error. On other modes - power outage may break last transaction and mdbx_chk can recover db in this case, see '-t' and '-0|1|2' options., label: chaindata, trace: [kv_mdbx.go:244 node.go:340 node.go:343 backend.go:191 node.go:113 main.go:62 command.go:271 app.go:333 app.go:310 main.go:37 proc.go:250 asm_amd64.s:1571]"
mdbx_env_open: MDBX_CORRUPTED: Maybe free space is over on disk. Otherwise it's hardware failure. Before creating issue please use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk. To handle hardware risks: use ECC RAM, use RAID of disks, run multiple application instances (or do backups). If hardware checks passed - check FS settings - 'fsync' and 'flock' must be enabled.  Otherwise - please create issue in Application repo. On default DURABLE mode, power outage can't cause this error. On other modes - power outage may break last transaction and mdbx_chk can recover db in this case, see '-t' and '-0|1|2' options., label: chaindata, trace: [kv_mdbx.go:244 node.go:340 node.go:343 backend.go:191 node.go:113 main.go:62 command.go:271 app.go:333 app.go:310 main.go:37 proc.go:250 asm_amd64.s:1571]

**please pack all the file in erigon data_dir including snapshots no just mdb file ,then test the archive file with lz4 -t** 

I've tries latest two verion  of  erigon_data_xx.tar.lz4 file ,none of them works properly.
I'd like to run a full archive node but it'll taken almost 2 mouth to completely sync

**Comment by kris-ss** [comment]
Hello, it looks like your extraction did not complete successfully. Maybe you are already out of storage.  Can confirm if you have enough storage? Note that the snapshot is about 1.8 TB

**Comment by kris-ss** [comment]
@justforfunya the snapshot url has been updated. Please try again now - https://pub-10cd0733ed3540f1a5bd893cdcaf4027.r2.dev/erigon_data_20230109.tar.lz4

**Comment by zhy827827** [comment]
ubuntu@rockx-mainnet-gcp-bsc-01:/opt/rockx$ tar -I lz4 -xvf erigon_data_20230109.tar.lz4
tar: Removing leading `/' from member names
/server1/home/qa/eri/erigon/data/chaindata/mdbx.dat


Error 68 : Unfinished stream
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

I have 9TB free storage. total extraction size is about 6T

**Comment by kris-ss** [comment]
We are checking this with the team.

**Comment by let4be** [comment]
Why wasn't readme updated? I just wasted half a day downloading and unpacking a broken snapshot...
