### ISSUE TITLE
Can't download snapshots for  erigon BSC Archive

### ISSUE THREAD

**Issue by zhy827827** [bnb-chain/bsc-snapshots#207]
when download this url: https://download.bsc-snapshot.workers.dev/erigon-data-20221227.tar.lz4：ERROR 404: Not Found.

Which URL can I download erigon BSC Archive???

**Comment by ZiyuanStar** [comment]
The link is unavailable atm, will have it fixed.

**Comment by zhy827827** [comment]
give me a erigon BSC Archive download url?

**Comment by ZiyuanStar** [comment]
it's fixed: https://pub-10cd0733ed3540f1a5bd893cdcaf4027.r2.dev/erigon_data_20230109.tar.lz4
