### ISSUE TITLE
erigon_data_20230109.tar.lz4 can't decompress

### ISSUE THREAD

**Issue by zhy827827** [bnb-chain/bsc-snapshots#208]
$ tar -I lz4 -xvf erigon_data_20230109.tar.lz4
tar: Removing leading `/' from member names
/server1/home/qa/eri/erigon/data/chaindata/mdbx.dat

Error 68 : Unfinished stream
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by kris-ss** [comment]
We are checking this with the team.

**Comment by zhy827827** [comment]
Please tell me how to decompress the snapshot？？
Look at my operation process：
1、 aria2c -s14 -x14  https://pub-10cd0733ed3540f1a5bd893cdcaf4027.r2.dev/erigon_data_20230109.tar.lz4
2、tar -I lz4 -xvf erigon_data_20230109.tar.lz4

tar: Removing leading `/' from member names
/server1/home/qa/eri/erigon/data/chaindata/mdbx.dat
Error 68 : Unfinished stream
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by zhy827827** [comment]
Please tell me how to decompress the snapshot？？
Look at my operation process：
1、 aria2c -s14 -x14 https://download.bsc-snapshot.workers.dev/erigon_data_20230109.tar.lz4
2、tar -I lz4 -xvf erigon_data_20230109.tar.lz4

tar: Removing leading `/' from member names
/server1/home/qa/eri/erigon/data/chaindata/mdbx.dat
Error 68 : Unfinished stream
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by kris-ss** [comment]
Hello, sorry for the inconvenience. The team is working on uploading a new snapshot. However, they may need about ~9 hours to upload the new one. Appreciate your patience.

**Comment by zhy827827** [comment]
As long as it is the correct snapshot, no matter how slow it is

**Comment by kris-ss** [comment]
Hello, a new snapshot has been uploaded. Please with new one - https://download.bsc-snapshot.workers.dev/erigon_data_20230112.tar.lz4

**Comment by zhy827827** [comment]
ok
