### ISSUE TITLE
Old snapshot?

### ISSUE THREAD

**Issue by fmira21** [bnb-chain/bsc-snapshots#210]
Hi guys!
I have just deployed your latest snapshot:
[geth-20230118.tar.lz4](https://download.bsc-snapshot.workers.dev/geth-20230118.tar.lz4)

But as far as I can see, the sync started with the blocks 1 month old:

```
INFO [01-19|16:54:01.157] Imported new chain segment               blocks=8 txs=1121 mgas=135.310 elapsed=1.852s    mgasps=73.026 number=23,867,074 hash=6267a6..7c1cf3 age=1mo1w5h dirty=1.57MiB
INFO [01-19|16:54:05.435] Imported new chain segment               blocks=29 txs=4131 mgas=434.801 elapsed=4.277s    mgasps=101.656 number=23,867,103 hash=a167ee..1d40ef age=1mo1w5h dirty=1.63MiB
```

What is wrong?

Thank you in advance!

**Comment by isaacyuno** [comment]
Replied in discord, please remove --gcmode=archive

**Comment by fmira21** [comment]
@isaacyuno 
Thank you! Now it's completely understandable.
