### ISSUE TITLE
Broken snapshot link

### ISSUE THREAD

**Issue by mantasak** [bnb-chain/bsc-snapshots#213]
The snapshot link **https://download.bsc-snapshot.workers.dev/geth-20230206.tar.lz4** is broken and returns a 404.

**Comment by lukasdhum** [comment]
+1

Previously the link worked but the version was more than 1 month old. Why is this maintained so poorly?

**Comment by kris-ss** [comment]
Hello, thank you for the feedback. The team is aware and is looking in to it. 

Please use https://download.bsc-snapshot.workers.dev/geth-20230204.tar.lz4 in the meantime.
