### ISSUE TITLE
Advice: shrink the snapshot file size, by delete history blocks.

### ISSUE THREAD

**Issue by brilliant-lx** [bnb-chain/bsc-snapshots#217]
The latest bsc-snapshot file is too large, `geth-20230210.tar.lz4` takes ~1.8TB.

48Club provides a smaller snapshot file without history block,  which is ~350GB.
But if most of the node in BSC network no longer contain history block, it could make the node sync very difficult to find good peer, in case it needs to sync the old blocks.

Further investigation is needed to address this issue.

**Comment by isaacyuno** [comment]
Could we provide both shrinked and unshrinked snapshots?

**Comment by du5** [comment]
Full node is generated with --tries-verify-mode=local

https://github.com/48Club/bsc-snapshots#full-node
