### ISSUE TITLE
Is there a new erigon of BSC archive snapshot?

### ISSUE THREAD

**Issue by Liamlu28** [bnb-chain/bsc-snapshots#219]
I can only see January, but not February.
https://download.bsc-snapshot.workers.dev/erigon_data_20230112.tar.lz4

**Comment by brilliant-lx** [comment]
the cloud service is broken, working on it.

**Comment by Mercybudda** [comment]
@Liamlu28 
Try to use this updated one pls: https://download.bsc-snapshot.workers.dev/erigon_data_20230213.tar.lz4

**Comment by Liamlu28** [comment]
> @Liamlu28 Try to use this updated one pls: https://download.bsc-snapshot.workers.dev/erigon_data_20230213.tar.lz4

Thanks!
