### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by etGitOne** [bnb-chain/bsc-snapshots#227]
The snapshot link https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230221.tar.lz4 returns 404.

**Comment by deepcrazy** [comment]
Hello, Thank you for the feedback. The team is aware and is looking in to it.

Please use https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230220.tar.lz4 in the meantime.
