### ISSUE TITLE
Erigon alternative full history snapshots available

### ISSUE THREAD

**Issue by miohtama** [bnb-chain/bsc-snapshots#228]
Hi all,

[We have created an alternative blockchain data snapshot for BNB Smart Chain for Erigon full nodes and detailed this process in a lengthy blog post](https://tradingstrategy.ai/blog/bnb-chain-erigon-snapshot). The current snapshot is for Feb 2023. The snapshot is with full transaction history (receipts, txs), making it possible to read past transactions, but not the past state (archive node). As  far as I know this is not possible with the official Erigon snapshot.

Compared to Geth, Erigon takes less disk space and is faster, so it is many times more performant option to run an EVM node.

The BNB Smart Chain snapshots are now publicly available to download from the Storj bucket.  A sync from scratch took somewhere around a month, so it is not an option for inpatient.

In the post, you can find 

- What is BNB Chain
- What is Erigon (one of EVM-compatible node applications)
- What is Storj and its decentralised storage
- What is a chain snapshot, and why are they important
- Compressing ~4 TB data to 1.2 TB using Zstd, and notes and ideas of the compression ratio of blockchain data, Zstd, ZFS
- How Storj is optimal (cost, efficiency) for distributing these kinds of files e.g. over Amazon S3
- Instructions on how to set up your own Erigon and use the snapshot
- Instructions and scripts on how to set up your snapshots stored on Storj

Happy to hear any feedback. Also happy to hear if we can help the BNB Chain team to host alternative Erigon snapshots in the future.

**Comment by subtletech** [comment]
@miohtama Hi. I've tried to follow your instructions, but it looks like your storj bucket `sj://bnb-chain-snapshot` is just empty. Would appreciate if you made it working again. Thanks.
