### ISSUE TITLE
Cannot start node from snapshot "geth-20230224.tar.lz4"

### ISSUE THREAD

**Issue by ngoisaoquay** [bnb-chain/bsc-snapshots#229]
HI team, please help to check snapshot file [geth-20230224.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230224.tar.lz4), I tried run it so many time but always get this error
./geth_linux --config ./config.toml --datadir ./geth  --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0
INFO [02-26|01:24:01.887] Starting Geth on Ethereum mainnet...
INFO [02-26|01:24:01.895] Maximum peer count                       ETH=30 LES=0 total=30
INFO [02-26|01:24:01.895] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [02-26|01:24:01.895] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
Fatal: Failed to register the Ethereum service: database contains incompatible genesis (have 0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b, new d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3)

this is log bsc.log
tail -f geth/bsc.log
t=2023-02-26T01:41:52+0100 lvl=warn msg="Truncating dangling indexes"      database=/data/geth/chaindata/ancient table=receipts indexed="89.04 KiB"   stored="0.00 B"
t=2023-02-26T01:41:52+0100 lvl=warn msg="Truncating dangling indexes"      database=/data/geth/chaindata/ancient table=receipts indexed="51.24 KiB"   stored="0.00 B"
t=2023-02-26T01:41:52+0100 lvl=warn msg="Truncating dangling indexes"      database=/data/geth/chaindata/ancient table=receipts indexed="25.88 KiB"   stored="0.00 B"
t=2023-02-26T01:41:52+0100 lvl=warn msg="Truncating freezer table"         database=/data/geth/chaindata/ancient table=headers  items=17,104,180 limit=14,711,641
t=2023-02-26T01:41:52+0100 lvl=warn msg="Truncating freezer table"         database=/data/geth/chaindata/ancient table=hashes   items=25,854,419 limit=14,711,641
t=2023-02-26T01:41:52+0100 lvl=warn msg="Truncating freezer table"         database=/data/geth/chaindata/ancient table=bodies   items=14,723,616 limit=14,711,641
t=2023-02-26T01:41:52+0100 lvl=warn msg="Truncating freezer table"         database=/data/geth/chaindata/ancient table=diffs    items=25,854,419 limit=14,711,641
t=2023-02-26T01:41:52+0100 lvl=info msg="AncientDB item count"             items=14,711,641
t=2023-02-26T01:41:52+0100 lvl=info msg="Opened ancient database"          database=/data/geth/chaindata/ancient readonly=false frozen=14,711,641
t=2023-02-26T01:41:52+0100 lvl=info msg="Persisted trie from memory database" nodes=12356 size="1.78 MiB" time=22.211982ms gcnodes=0 gcsize="0.00 B" gctime=0s livenodes=1 livesize="0.00 B"

**Comment by isaacyuno** [comment]
Are you using latest config files mainnet.zip from https://github.com/bnb-chain/bsc/releases/tag/v1.1.19?

**Comment by ngoisaoquay** [comment]
Yes, I did. I tried to run on 2 machines but I got the same error, I’m waiting for the next snapshot file and I will try it again

**Comment by etiennelunetta** [comment]
Hey, I've tried both this snapshot and `geth-20230226.tar.lz4` with the latest configs. Getting seemingly endless `Truncating dangling indexes` `WARN` logs.

**Comment by cosinlink** [comment]
uploaded new version, thanks for reporting this issue

**Comment by etiennelunetta** [comment]
This is still happening with the latest version afaict
