### ISSUE TITLE
Impossible to uncompress snapshot

### ISSUE THREAD

**Issue by banlieu451** [bnb-chain/bsc-snapshots#231]
Hello i have a bug every time i try to uncompress the file after doing this :

`tar -I lz4 -xvf geth.tar.lz4`

i get this : 

![Sans titre](https://user-images.githubusercontent.com/76543738/221458075-f55149ce-4cf2-44bb-b0e7-00d99de0305c.png)

**Comment by isaacyuno** [comment]
We are checking on this snapshot and will provide a fixed one

**Comment by ngoisaoquay** [comment]
Yes, I got with same error, and cannot start fullnode, please help to check this

**Comment by ngoisaoquay** [comment]
Hi @isaacyuno any update on this?

**Comment by banlieu451** [comment]
Where did we can find other realease, to try ?

**Comment by cosinlink** [comment]
uploaded new version,  thanks for reporting

**Comment by ngoisaoquay** [comment]
I still see this file "[geth-20230226.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230226.tar.lz4)" is it right?

**Comment by ngoisaoquay** [comment]
![image](https://user-images.githubusercontent.com/46889432/221785443-3357feec-6dc8-46a4-9e68-517ba2c17aea.png)
I still got this error @cosinlink

**Comment by ngoisaoquay** [comment]
Could you please help to check it before public it to this? it take too long time every time I download and extract it.

**Comment by ngoisaoquay** [comment]
If I try to run on this snapshot, It showing 
![image](https://user-images.githubusercontent.com/46889432/221787919-9e29bfb4-6e28-4570-bfe3-41386803acd6.png)
then it will be clear all the data and sync from 0x0.

**Comment by MindPhaser34** [comment]
Link for snapshot file([geth-20230228.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230228.tar.lz4)) is dead =( 
![image](https://user-images.githubusercontent.com/29473640/221817505-58f6ddf4-618c-4b6d-a69b-610ffe832593.png)

**Comment by MindPhaser34** [comment]
looks like the link has been repaired. :tada:
let's try to download and unpack...

**Comment by MindPhaser34** [comment]
Now everything is fine. 
![image](https://user-images.githubusercontent.com/29473640/222616858-bdf568c9-7e4a-4a6c-97d6-e567c0243457.png)

**Comment by BoogalooLi** [comment]
> The link to the snapshot file([geth-20230228.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230228.tar.lz4)) is dead =( ![image](https://user-images.githubusercontent.com/29473640/221817505-58f6ddf4-618c-4b6d-a69b-610ffe832593.png)

link is not available now. i want this snapshot because we meet the same error as metioned

**Comment by brilliant-lx** [comment]
> > The link to the snapshot file([geth-20230228.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230228.tar.lz4)) is dead =( ![image](https://user-images.githubusercontent.com/29473640/221817505-58f6ddf4-618c-4b6d-a69b-610ffe832593.png)
> 
> link is not available now. i want this snapshot because we meet the same error as metioned

no longer availabled.
