### ISSUE TITLE
Geth Torrent Snapshot 01/03/2023 Uncompressed

### ISSUE THREAD

**Issue by 0x090909** [bnb-chain/bsc-snapshots#233]
Hello guys, I just pruned my node and I created a torrent for the snapshot for today 01/03/2023.

Torrent has been created from extracted archive so no need to uncompress.

TOTAL SIZE OF PRUNED SNAPSHOT: 832.11 GB 
TOTAL SIZE OF TORRENT: 28.6 MB
NUMBER OF FILES: 389474

Snapshot is ancient and state pruned.

Link for torrent: https://easyupload.io/ernwjh
Magnet: magnet:?xt=urn:btih:d4f9727c70b123ba8b69e662b27251a70555a963&dn=node&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce

Enjoy

**Comment by cosinlink** [comment]
What is the download link you used ?

**Comment by 0x090909** [comment]
I uploaded the torrent here: https://easyupload.io/ernwjh Im seeding it.
