### ISSUE TITLE
The latest  snapshots can't download .How to download the latest  snapshot?

### ISSUE THREAD

**Issue by atlasW** [bnb-chain/bsc-snapshots#235]
Hi:
why The latest link can't download ? is it disable Public access ?? How to download the latest snapshot?

**Comment by kris-ss** [comment]
Thanks for the feedback. The team is fixing this. In the meantime, please use an older snapshot - https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230308.tar.lz4
