### ISSUE TITLE
Can't download erigon_data_20230220.tar.lz4

### ISSUE THREAD

**Issue by zhy827827** [bnb-chain/bsc-snapshots#236]
wget -q -O - https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20230220.tar.lz4 | tar -I lz4 -xvf -
tar: Removing leading `/' from member names
/server1/home/qa/eri/erigon/data/chaindata/mdbx.dat
Error 68 : Unfinished stream
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

```
03/21 02:03:22 [NOTICE] Downloading 1 item(s)

03/21 02:03:22 [ERROR] CUID#7 - Download aborted. URI=https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20230220.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20230220.tar.lz4
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found
```

Please solve the problem officially!

**Comment by VFedorV** [comment]
hello. could you fix the [download link](https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20230220.tar.lz4) - still getting 404 error:
`--2023-04-06 11:38:52--  http://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20230220.tar.lz4
Распознаётся pub-60a193f9bd504900a520f4f260497d1c.r2.dev (pub-60a193f9bd504900a520f4f260497d1c.r2.dev)… 188.114.99.224, 188.114.98.224
Подключение к pub-60a193f9bd504900a520f4f260497d1c.r2.dev (pub-60a193f9bd504900a520f4f260497d1c.r2.dev)|188.114.99.224|:80... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 301 Moved Permanently
Адрес: https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20230220.tar.lz4 [переход]
--2023-04-06 11:38:53--  https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20230220.tar.lz4
Подключение к pub-60a193f9bd504900a520f4f260497d1c.r2.dev (pub-60a193f9bd504900a520f4f260497d1c.r2.dev)|188.114.99.224|:443... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 404 Not Found
2023-04-06 11:38:53 ОШИБКА 404: Not Found.`

**Comment by kris-ss** [comment]
Sorry for the inconvenience, the team is looking into this. Will feedback as soon as it is fixed.
