### ISSUE TITLE
Erigon snapshot erigon-0410.tar.lz4 decompression failed

### ISSUE THREAD

**Issue by zhy827827** [bnb-chain/bsc-snapshots#245]
$ wget -q -O - https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon-0410.tar.lz4 |tar -I lz4 -xvf -
server/bsc-erigon/data/chaindata/mdbx.dat
Error 68 : Unfinished stream
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by zhy827827** [comment]
So while other chains manage to publish daily snapshots, Binance needs two days and and an entire team to (not) fix the download of an 12 day old snapshot? How about Binance just pays someone the 2k/month necessary to do this properly? Alternatively maybe make your software less fragile so users don't need to download a new snapshot every few weeks ...

Really, unbelievable how you can not even manage to do a simple task like this properly with the same problems happening again and again and again. Broken snapshots, broken links, nohup'ed garbage without any error checking apparently. This is not rocket science. Especially considering all the money Binance made of BSC and their financial power behind it.

**Comment by admincheg** [comment]
Error still exists. I've try to download twice and each time I've got

root@bsc1:/srv/bsc# tar -I lz4 -xvf erigon.tar.lz4
server/bsc-erigon/data/chaindata/mdbx.dat
Error 66 : Decompression error : ERROR_decompressionFailed
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

Download process was interrupted from another side at least once in half of hour, but continue by aria2c:

```
[#2d028b 1,766GiB/2,348GiB(75%) CN:8 DL:111MiB ETA:1h29m16s]
04/24 13:07:05 [ERROR] CUID#21 - Download aborted. URI=https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon-0410.tar.lz4
Exception: [DownloadCommand.cc:234] errorCode=1 Got EOF from the server.
 *** Download Progress Summary as of Mon Apr 24 13:07:37 2023 ***
[#2d028b 1,830GiB/2,348GiB(77%) CN:7 DL:111MiB ETA:1h19m26s]
04/24 13:16:55 [ERROR] CUID#7 - Download aborted. URI=https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon-0410.tar.lz4
Exception: [DownloadCommand.cc:234] errorCode=1 Got EOF from the server.
 *** Download Progress Summary as of Mon Apr 24 13:17:43 2023 ***
[#2d028b 1,900GiB/2,348GiB(80%) CN:6 DL:111MiB ETA:1h8m26s]
04/24 13:27:38 [ERROR] CUID#14 - Download aborted. URI=https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon-0410.tar.lz4
Exception: [DownloadCommand.cc:234] errorCode=1 Got EOF from the server.
 *** Download Progress Summary as of Mon Apr 24 13:27:48 2023 ***
[#2d028b 1,980GiB/2,348GiB(84%) CN:5 DL:111MiB ETA:56m38s]
04/24 13:39:55 [ERROR] CUID#15 - Download aborted. URI=https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon-0410.tar.lz4
Exception: [DownloadCommand.cc:234] errorCode=1 Got EOF from the server.
 *** Download Progress Summary as of Mon Apr 24 13:39:55 2023 ***
[#2d028b 2,182GiB/2,348GiB(92%) CN:3 DL:84MiB ETA:33m33s]
04/24 14:12:36 [ERROR] CUID#12 - Download aborted. URI=https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon-0410.tar.lz4
Exception: [DownloadCommand.cc:234] errorCode=1 Got EOF from the server.
 *** Download Progress Summary as of Mon Apr 24 14:13:16 2023 ***
[#2d028b 2,331GiB/2,348GiB(99%) CN:2 DL:57MiB ETA:5m18s]
04/24 14:57:52 [ERROR] CUID#10 - Download aborted. URI=https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon-0410.tar.lz4
Exception: [DownloadCommand.cc:234] errorCode=1 Got EOF from the server.
 *** Download Progress Summary as of Mon Apr 24 14:58:36 2023 ***
```

Can you provide another one consistent snapshot which will work?

**Comment by delid4ve** [comment]
Anyone have an erigon snapshot that works? Takes a couple days to download restricted by the server at 34mb/s and now the decompression failed error.
Already on the second attempt as files changed size mid download last week.
