### ISSUE TITLE
smartchain node `stuck`

### ISSUE THREAD

**Issue by kasrakhamesi** [bnb-chain/bsc-snapshots#248]
![image](https://user-images.githubusercontent.com/80700084/236327646-691f2a4c-ebe2-4dc5-90a2-4995c3170291.png)

after 4 days,smartchain node only show me `New local node record ` message and can't import new block,
last syncing is : {
  currentBlock: 26799399,
  highestBlock: 27921507,
  knownStates: 297473485,
  pulledStates: 297473485,
  startingBlock: 26799399
}

I using this command to get config.toml and genesis.json file : 

wget   $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4)
unzip mainnet.zip

and trying with this mainnet config too : 
https://github.com/bnb-chain/bsc/releases/download/v1.1.8/mainnet.zip

my docker command for running node : 

docker run -v /root/chaindata/smartchain/config:/home/config -v /root/chaindata/smartchain/server/data-seed:/home/node -p 8545:8545 -p 8546:8546 --rm --name bsc -it dysnix/bsc:v1.1.8 --config /home/config/config.toml --http.addr 0.0.0.0 --http.vhosts '*' --datadir /home/node

please help me :((

**Comment by ZiyuanStar** [comment]
duplicate with https://github.com/bnb-chain/bsc/issues/1570
