### ISSUE TITLE
Latest snapshot is over 3 weeks old even though it's dated May 2nd.

### ISSUE THREAD

**Issue by Crypto2** [bnb-chain/bsc-snapshots#249]
n/t

**Comment by ZiyuanStar** [comment]
will check it

**Comment by du5** [comment]
You can use snapshot provided by 48Club

https://github.com/48Club/bsc-snapshots#full-node

**Comment by Crypto2** [comment]
Yeah was just letting them know so they could fix it or maybe save someone else wasting 2 days downloading it.

**Comment by nabilmahat** [comment]
> You can use snapshot provided by 48Club
> 
> https://github.com/48Club/bsc-snapshots#full-node

@du5 but this one dont have MPT data right?

**Comment by du5** [comment]
> > You can use snapshot provided by 48Club
> > https://github.com/48Club/bsc-snapshots#full-node
> 
> @du5 but this one dont have MPT data right?

Suggest reading readme
