### ISSUE TITLE
Update snapshot?

### ISSUE THREAD

**Issue by B1Q** [bnb-chain/bsc-snapshots#254]
Snapshot is 11 days old, any way to get a new one? Geth has been syncing for 4 days and it still hasn't caught up.

**Comment by nabilmahat** [comment]
Which one are you using? I use this snapshot https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230502.tar.lz4 and it is 3weeks old

**Comment by B1Q** [comment]
> Which one are you using? I use this snapshot https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230502.tar.lz4 and it is 3weeks old

the problem is that this snapshot has been syncing for the past week and it's still not fully synced not even to a recent block there's still more than 1 week of data unsynced

the most recent snapshot (they updated it to 05 16) is not even decompressing on windows hahahaha shit is wild for a Windows user like myself

**Comment by brilliant-lx** [comment]
the latest is: geth-20230516.tar.lz4
ok for you?
I think we need figure out some solution to improve the UX of snapshot, I created an issue to track: https://github.com/bnb-chain/bsc-snapshots/issues/260
welcome to give some suggestion.

**Comment by shivraj001** [comment]
@brilliant-lx  is there any snapshot available for testnet? could you please help here?
