### ISSUE TITLE
prefixab is returning 404. 

### ISSUE THREAD

**Issue by densone** [bnb-chain/bsc-snapshots#257]
Trying to download snapshot and seems to be returning a 404. 

<img width="852" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/49484/112f1999-c47c-459c-b97e-0dd6b20e2c7c">

**Comment by deepcrazy** [comment]
Hi there, Are you trying to download it using `aria2c` command? If so, try to re-run to same `aria2c` command as it can happen that aria2c may fail sometimes as mentioned here: https://github.com/bnb-chain/bsc-snapshots#usage.

Also, share which command you're using to download?

P.S: You can also try out this: `nohup aria2c -o geth.tar.lz4 -s14 -x14 -k100M https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230516.tar.lz4 -o geth.tar.lz4 &` to download it.

**Comment by icculp** [comment]
Same here, trying to download `aria2c -s14 -x14 -k100M https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/chunk/prefixab` fails, the rest (a-e) work fine but b fails. This is the erigon snapshot deepcrazy, not geth

**Comment by broyeztony** [comment]
@deepcrazy any updates on this ? 
https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/chunk/prefixab is really missing.

**Comment by brilliant-lx** [comment]
uploading, it takes time, since the file is very large, probably will be done within 12hours.

**Comment by brilliant-lx** [comment]
sorry, there is still a missing part, we tried several time, but always failed.
Now, we will split the file into several smaller one and upload again, hope it works

**Comment by densone** [comment]
Hey @brilliant-lx  take a look at how polygon does their snapshots. They supply a file list and you can use aria2 to download the file list. Works quite well.  

https://snapshots.polygon.technology

From there you can do something like: 

```bash
aria2c https://snapshot-download.polygon.technology/heimdall-mumbai-incremental-compiled-files.txt

#then

aria2c -x6 -j6 -I https://snapshot-download.polygon.technology/heimdall-mumbai-incremental-compiled-files.txt
```

**Comment by brilliant-lx** [comment]
the snapshot is updated, @broyeztony @densone 

And thank you for you input, it looks like it would be much easier to download the snapshot, no long need to copy/paste the latest snapshot url.

I will create an issue to track this request.

**Comment by brilliant-lx** [comment]
The tracking issue: https://github.com/bnb-chain/bsc-snapshots/issues/260
Welcome to give more feedback, thx
