### ISSUE TITLE
LongTerm: Improve the UX of snapshot download

### ISSUE THREAD

**Issue by brilliant-lx** [bnb-chain/bsc-snapshots#260]
## More
Since the data is becoming more and more huge, it is not each to upload/download these files.
Welcome to give more suggestion to improve the UX of snapshot download, you may just reply this ticket.

## Some Ideas
- Data checkpoint, like make a checkpoint of 2023.01.01, users only need to download once and kept it in their disk. Next time, they only need to the incremental part, which would be much smaller.
- provide a fixed url to describe the snapshot download urls, so users no longer need to copy/paste the update the snapshot urls. see: https://github.com/bnb-chain/bsc-snapshots/issues/257

## Feedback
> to be collected

**Comment by densone** [comment]
A quick point of advice. When you run the split command switch `prefix` to a logical prefix.  `BSC-26-05-2023-`
