### ISSUE TITLE
I am not totally sure this will work

### ISSUE THREAD

**Issue by densone** [bnb-chain/bsc-snapshots#261]
The readme states you can run the following command. 

`cat /chunk* > mdbx.tar.lz4`

You have file A and B but B is split n times.  

If you run the `cat chunk*` to stream the files back together out of order especially with `CHUNK B`. You may be unable to extract.  I did this and was only able to extract part of the lz4 file.  

I wrote a quick script and attempting again in order of split. 

```bash
chunks="chunkaa chunkb1 chunkb2 chunkb3 chunkac chunkad chunkae"

for i in $chunks
do
     echo "Catting  $i"
     cat $i >> mdbx.tar.lz4
done

```

**Comment by 0xLyon** [comment]
Hi there, please note that the URLs are not all the same for the mentioned chunks and thus could be why you are only able to extract part of the .lz4

For chunks “a, c-e”: 
nohup aria2c -s14 -x14 -k100M https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/chunk0523/chunka{<chunk_char>}

For splitted “b” chunks: 
nohup aria2c -s14 -x14 -k100M https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/chunkb{<splitted_chunk_b_no>}

You can find the pull paths for each here - https://github.com/bnb-chain/bsc-snapshots#endpoint-1
