### ISSUE TITLE
节点不同步了

### ISSUE THREAD

**Issue by zh5715615** [bnb-chain/bsc-snapshots#262]
我的节点同步区块到27149618的高度后就不动了，重新拉取最新的区块高度，还是再27149618这个高度。这是什么原因导致？

**Comment by ZiyuanStar** [comment]
geth用的哪个版本？启动命令是什么？

**Comment by zh5715615** [comment]
geth版本是Version: 1.1.20
启动命令是：geth --config ./config.toml --datadir ./node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0 --syncmode=full --tries-verify-mode=local

**Comment by ZiyuanStar** [comment]
geth 版本升级后重启再试下

**Comment by zh5715615** [comment]
我怀疑过这个问题，也升级了没起到作用，可能升的版本不对，请问要升级到哪个版本
