### ISSUE TITLE
Does the snapshots contains the pruned data instead of the full data?

### ISSUE THREAD

**Issue by shiziwen** [bnb-chain/bsc-snapshots#263]
Hi, does the snapshots contains the pruned data instead of the full data?

Hi, I have run two bsc fullnodes, but I can get block data after block number "19144096". All eth.getBlock from Block 1 to 19144096 return null, however, from 19144097 to lastBlockNumber it returns data.
```
curl --location 'http://127.0.0.1:8545/' \
--header 'Content-Type: application/json' \
--data '[
    {
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": [
        "0x1241da0",
        false
    ],
    "id": 1
    }
]'
```

```
curl --location 'http://127.0.0.1:8545/' \
--header 'Content-Type: application/json' \
--data '[
    {
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": [
        "0x1",
        false
    ],
    "id": 1
    }
]'
```

these two commands return null.

And I sync from the snapshot, https://download.bsc-snapshot.workers.dev/geth-20220816.tar.lz4.

If snapshot only has data from a certain block number, you should mention it in the notes!!!

**Comment by du5** [comment]
maybe u need archive node

**Comment by shiziwen** [comment]
> maybe u need archive node

Hi, I just want to fetch the basic history data, for example, the block and tx info.

So I think I don't need the archive node.

**Comment by Dukdig2325** [comment]
> Hi, does the snapshots contains the pruned data instead of the full data?
> 
> Hi, I have run two bsc fullnodes, but I can get block data after block number "19144096". All eth.getBlock from Block 1 to 19144096 return null, however, from 19144097 to lastBlockNumber it returns data.
> ```
> curl --location 'http://127.0.0.1:8545/' \
> --header 'Content-Type: application/json' \
> --data '[
>     {
>     "jsonrpc": "2.0",
>     "method": "eth_getBlockByNumber",
>     "params": [
>         "0x1241da0",
>         false
>     ],
>     "id": 1
>     }
> ]'
> ```
> 
> ```
> curl --location 'http://127.0.0.1:8545/' \
> --header 'Content-Type: application/json' \
> --data '[
>     {
>     "jsonrpc": "2.0",
>     "method": "eth_getBlockByNumber",
>     "params": [
>         "0x1",
>         false
>     ],
>     "id": 1
>     }
> ]'
> ```
> 
> these two commands return null.
> 
> And I sync from the snapshot, https://download.bsc-snapshot.workers.dev/geth-20220816.tar.lz4.
> 
> If snapshot only has data from a certain block number, you should mention it in the notes!!!
> 
> 
>

**Comment by yxt181110417** [comment]
hi, have you solved the problem?
