### ISSUE TITLE
Erigon - pruned instead of archive

### ISSUE THREAD

**Issue by serborg** [bnb-chain/bsc-snapshots#275]
Hi Erigon-BSC snapshots https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/chunk_20230625aa etc don't contain full archive data as they supposed to.

I believe the source node has pruning enabled for some data. mdbx_stat shows 90000-something blocks present in that file which is the default limit for pruning. I believe at source node the older data is moved to snapshots/ long-term storage but it is still available for the node so everything works fine. The new machines who use this state don't have this data as this snapshots/ long-term data are distributed via torrent by 500000 chunks only, also only after hashes added/approved by the developers.

This is manifested by
WARN[07-02|10:22:45.644] [1/15 Snapshots] Some blocks are not in snapshots and not in db max_in_snapshots=28499999 min_in_db=29317000
printed by Erigon. So it is not possible to query RPC for information for blocks 28500000-29317000.

Please upload full archive snapshot. Keep up great work!

**Comment by calmbeing** [comment]
@serborg ,thanks for your point, updated torrent hash here https://github.com/node-real/bsc-erigon-snapshot/pull/5/files, will be merged soon

**Comment by Wangpaipai** [comment]
I have also encountered the same problem as you. Have you resolved it?
