### ISSUE TITLE
Your link address is wrong.

### ISSUE THREAD

**Issue by presIey** [bnb-chain/bsc-snapshots#279]
#### [erigon_data_20230724_chunkag](https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/chunk_20230724ag)

There is an extra 0 in the last part of the link address of chunkaf. 'chunk_202307240af' should be 'chunk_20230724af'.

**Comment by 0xLyon** [comment]
Thanks will escalate to the respective team.
