### ISSUE TITLE
 geth-20230806.tar.lz4 is wrong?

### ISSUE THREAD

**Issue by zp43401591** [bnb-chain/bsc-snapshots#280]
I download geth-20230806.tar.lz4 and there is not include server/data-seed/geth/triecache. 
This file is about 1.6T, but geth-20230719.tar.lz4 is about 2.1T.
Is there something wrong with geth-20230806.tar.lz4 when it uploaded?

**Comment by deepcrazy** [comment]
Can you confirm if the download was successful w/o any error? Also, Can you send the screenshot of files/folders available after uncompressing the snapshot?

**Comment by loglapa** [comment]
same problem, archive is uncomplete

**Comment by zp43401591** [comment]
> Can you confirm if the download was successful w/o any error? Also, Can you send the screenshot of files/folders available after uncompressing the snapshot?

I have deleted those files and use genesis way to sync.

**Comment by loglapa** [comment]
same problem for https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230726.tar.lz4

**Comment by loglapa** [comment]
![image](https://github.com/bnb-chain/bsc-snapshots/assets/51929896/22a93476-b229-48f4-89f4-0366967e6885)
the downloaded archive weighs less than necessary
also when I unpack it I get an EOF error like for a broken one

**Comment by kaber2** [comment]
Same here. After complaints about this for as long as this repository exists, you guys still haven't manage to fix this trivial process. Good job there wasting people's time and bandwidth.

**Comment by appop** [comment]
Find the same problem,
server/data-seed/geth/chaindata/99633326.ldb
Error 68 : Unfinished stream
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by lijiehelloworld** [comment]
Same problem, we need a new snapshot

**Comment by dorijan** [comment]
Yes, downloaded it 3x, thought it was a download problem :(

**Comment by pluto9r** [comment]
The new snapshot also has the same problem. Maybe you can verify the snapshot before uploading next time?

**Comment by brilliant-lx** [comment]
Sorry for the trouble, there was a problem with the snapshot node recently, just recovered several days ago.
The previous one should be good.
https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230818.tar.lz4
