### ISSUE TITLE
Endpoint(Mainnet) snapshot is outdated.

### ISSUE THREAD

**Issue by wtdcode** [bnb-chain/bsc-snapshots#282]
It has been 3 weeks since last snapshot. Could you provide a new snapshot?

**Comment by 0xLyon** [comment]
Yes this will be updated soon. You can also look at using: https://github.com/48Club/bsc-snapshots

**Comment by wtdcode** [comment]
Thanks for reply! I also requested for a release there.

btw, how much storage does an archive node need at this moment? It is possible to fit into a 2*4T raid0 array (`df -h` says 7.3T)?

**Comment by 0xLyon** [comment]
7.3T is enough for BSC full node, but for archive node you would require roughly +-50T.
See details here: https://nodereal.io/blog/en/bnb-smartchain/

**Comment by wtdcode** [comment]
> 7.3T is enough for BSC full node, but for archive node you would require roughly +-50T. See details here: https://nodereal.io/blog/en/bnb-smartchain/

Oh sorry I should mention I'm using erigon.

**Comment by wtdcode** [comment]
Reading from [#82](https://github.com/48Club/bsc-snapshots/issues/82), looks like at this moment 7T is required for an erigon archive node (2 weeks ago at least).

**Comment by wtdcode** [comment]
Seems updated, I will close this. Thanks!

**Comment by du5** [comment]
<img width="533" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/54979375/36651d7b-3fe3-4ee4-9a78-fd12596ac264">
Suggestion(NVMe ≥ 9T)

**Comment by wtdcode** [comment]
```
792G	./snapshots
20K	./temp
6.4T	./chaindata
6.1M	./nodes
18M	./parlia
12K	./logs
7.1T	.
```

My final actual disk usage using bsc snapshots from binance official repo though bought 4T * 5 already.
