### ISSUE TITLE
geth-20230806.tar.lz4 不能解压

### ISSUE THREAD

**Issue by zhy827827** [bnb-chain/bsc-snapshots#283]
geth-20230806.tar.lz4 解压报错

/*stdin*\ : Decoding error (36) : Corrupted block detected
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by loglapa** [comment]
https://github.com/bnb-chain/bsc-snapshots/issues/280

**Comment by zhy827827** [comment]
Error 404
This object could not be viewed

**Comment by loglapa** [comment]
check previews issue _geth-20230806.tar.lz4 is wrong? #280_

**Comment by zhy827827** [comment]
geth-20230806.tar.lz4 can't decompress.I don't know if anyone else has such a problem

**Comment by dorijan** [comment]
Yes, I have the same issue, downloaded it twice already :( I thought it was corrupted while I was downloading it...
