### ISSUE TITLE
geth-20230821.tar.lz4 same problem as previous snapshot

### ISSUE THREAD

**Issue by pluto9r** [bnb-chain/bsc-snapshots#287]
Same issue as https://github.com/bnb-chain/bsc-snapshots/issues/280
The snapshot is corrupted/incomplete.

Please test the snapshot before uploading a new one.

**Comment by brilliant-lx** [comment]
Could you try the previous one?
https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230818.tar.lz4
