### ISSUE TITLE
geth-20230822.tar.lz4 snapshot does not download

### ISSUE THREAD

**Issue by jade-sung** [bnb-chain/bsc-snapshots#289]
When I try to download a snapshot with the command below, it does not download. At first, the error does not appear and seems to have started downloading, but nothing is going on. If I cancel and try again, the error will be returned from then on.
What's unusual is that it downloads when you press the link on Windows, but it doesn't download from mac and ubuntu.
Try 20230818.tar.lz4 and it's the same too.
There was no problem about two months ago, so could you tell me why?

1. wget -O geth.tar.lz4 https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230822.tar.lz4
>
--2023-08-29 08:10:11--  https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230822.tar.lz4
Resolving pub-c0627345c16f47ab858c9469133073a8.r2.dev (pub-c0627345c16f47ab858c9469133073a8.r2.dev)... 127.0.0.1
Connecting to pub-c0627345c16f47ab858c9469133073a8.r2.dev (pub-c0627345c16f47ab858c9469133073a8.r2.dev)|127.0.0.1|:443... failed: Connection refused.

2. aria2c -o geth.tar.lz4 -s14 -x14 -k100M https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230822.tar.lz4

**Comment by deepcrazy** [comment]
It's working fine. Do you have more logs when running via `aria2c`? Please try to run it in background and using the following command:
` nohup aria2c -o geth.tar.lz4 -s14 -x14 -k100M https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230822.tar.lz4 &`

And then you can the check the output from nohup.out file. You can re-run the same command, if it stops downloading and `aria2c` will automatically resume the download from where it was stuck/stopped.

Also, Make sure to disable any firewall settings if any.
