### ISSUE TITLE
Fatal: Unable to attach to remote geth: dial unix /home/bsc/.ethereum/geth.ipc: connect: connection refused

### ISSUE THREAD

**Issue by cexland** [bnb-chain/bsc-snapshots#290]
Getting "Fatal: Unable to attach to remote geth: dial unix /home/bsc/.ethereum/geth.ipc: connect: connection refused" when running ./geth_linux attach

**Comment by CocoStarZ** [comment]
You can refer to the solution here: https://github.com/ethereum/go-ethereum/issues/1908

**Comment by cexland** [comment]
asked in eth forums they told me need to ask in bsc channel

**Comment by brilliant-lx** [comment]
do you still have the issue?
