### ISSUE TITLE
geth-20230902.tar.lz4 Error 404

### ISSUE THREAD

**Issue by sahancava** [bnb-chain/bsc-snapshots#291]
Can you please update the URL for geth-20230902.tar.lz4

<img width="774" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/57447079/f7498d0f-be39-48b1-9548-6dc487fb1faf">

**Comment by coesensbert** [comment]
jep https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230902.tar.lz4 does not work

**Comment by bensacc** [comment]
having the same issue
