### ISSUE TITLE
geth-20231008 Cannot Download, Return 404

### ISSUE THREAD

**Issue by nqt123** [bnb-chain/bsc-snapshots#298]
Download link: https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20231008.tar.lz4 is not available 
Snapshot can't download, please update

**Comment by vilotgit** [comment]
It's not available for me as well...

**Comment by 0xLyon** [comment]
Thanks for reporting. The developers are looking into this and will be resolved shortly
