### ISSUE TITLE
Discussion on snapshot creation

### ISSUE THREAD

**Issue by abhishekk049** [bnb-chain/bsc-snapshots#30]
Hi ,
I was just wondering how is this snapshot created?
We already have a node running, how can we create a snapshot. if we can create a snapshot within our network internally , we can save time and data transfer cost for downloading the snapshot.

Also, if i spin up a new node using the older chaindata, the syncing is very slow in the new node. How can we make sure this does not happen.

**Comment by nftgeek** [comment]
Interesting

**Comment by BisonDee** [comment]
To create a snapshot, all you really need to do it stop your running node first to prevent data corruption. Then tar it up and restart your node to stay current.

**Comment by zigg76** [comment]
> 
> 
> To create a snapshot, all you really need to do it stop your running node first to prevent data corruption. Then tar it up and restart your node to stay current. If you want to reduce data gaps, you can keep a couple nodes running and tap them for snapshots

so all i have is to do is  tar /chaindata and /triecache folder and i have my snaphot ?

**Comment by BisonDee** [comment]
That's right. No real magic

**Comment by guagualvcha** [comment]
```
1. Stop the bsc node first.
2. Run nohup geth snapshot prune-state --datadir {the data dir of your bsc node} &. It will take 3-5 hours to finish.
```
And you will get a light chaindata directory. That is a snapshot.
