### ISSUE TITLE
erigon_data_20231030 archive snapshot  can not get history block

### ISSUE THREAD

**Issue by xjhweb** [bnb-chain/bsc-snapshots#306]
Returns null for all history blocks except the last few thousand.

**Comment by zfy0701** [comment]
it reports this after start

Some blocks are not in snapshots and not in db max_in_snapshots=28499999 min_in_db=32756000

**Comment by zzzckck** [comment]
pls create issue in https://github.com/node-real/bsc-erigon/issues
