### ISSUE TITLE
even the ancient data pruned snapshot is as large as 2.4TB?

### ISSUE THREAD

**Issue by Brion-L** [bnb-chain/bsc-snapshots#311]
here you provided several snapshots under the "Database after Ancient Data Prune" section: https://github.com/bnb-chain/bsc-snapshots#database-after-ancient-data-prune

While these snapshots are as large as 2.4TB, the full node snapshot provided by [48Club](https://github.com/48Club/bsc-snapshots) is only <700GB, both are full node snapshots. May I know what's the difference between your snapshot and 48Club's?

**Comment by CocoStarZ** [comment]
Ancient Data Prune is a new feature in [bsc v1.1.8](https://github.com/bnb-chain/bsc/releases/tag/v1.1.8), meaning you could prune it manually. 48club snapshot is already pruned. that's the difference.
