### ISSUE TITLE
Does testnet snapshot exist?  PBSS snapshots with pebble format

### ISSUE THREAD

**Issue by rayn316** [bnb-chain/bsc-snapshots#318]
Can you provide snapshots of the testnet network in PBSS snapshots with pebble format?
Because the Kepler hard fork is coming, but the synchronization cannot be completed

**Comment by deepcrazy** [comment]
Team is working on uploading Testnet snap using PBSS with pebble DB. No hard ETA yet but It'll be probably done by tmr or day after tmr. Thx.

**Comment by flywukong** [comment]
You can download it on  [snap](https://github.com/bnb-chain/bsc-snapshots)

**Comment by rayn316** [comment]
i get it now, thank you.
