### ISSUE TITLE
PBSS snapshot does not work with --tries-verify-mode=none

### ISSUE THREAD

**Issue by web3dev2023** [bnb-chain/bsc-snapshots#324]
Hi, I downloaded the latest pbss pebble snapshot for [mainnet](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20231217.tar.lz4) and ran the following on Windows (bsc client version v1.3.7):
`C:\Users\administrator\geth_windows.exe --config C:\Users\administrator\config.toml --datadir c:/bsc --ws --rpc.allow-unprotected-txs --history.transactions 0  --state.scheme path   --tries-verify-mode  none --db.engine pebble`

And then I got the error
`Fatal: incompatible state scheme, stored: path, config: hash, CLI: path`

Is there a fix to it?

**Comment by STdevK** [comment]
you can check here https://github.com/bnb-chain/bsc/issues/2092

**Comment by web3dev2023** [comment]
Thanks!
I added
```
[Eth]
StateScheme = "path"
```
to `config.toml` 
and it works.

**Comment by web3dev2023** [comment]
Sorry, there is another problem.
I can use ` --tries-verify-mode  none` without any pruning. However, there will be another error after ancient pruning.

After syncing with `--syncmode full --pruneancient`, if I use  ` --tries-verify-mode  none` ,  I get the following error:

`Fatal: Could not open database: open c:\bsc\chaindata\ancient\chain\headers.cidx: The system cannot find the file specified.`

Seems someone else is haveing the same problem https://github.com/bnb-chain/bsc/issues/2110#issue-2056511631

**Comment by brilliant-lx** [comment]
> Sorry, there is another problem. I can use ` --tries-verify-mode none` without any pruning. However, there will be another error after ancient pruning.
> 
> I first synced with `--syncmode full --pruneancient` to reduce the size of the database. Then I removed these 2 flags and used ` --tries-verify-mode none` , but get following error:
> 
> `Fatal: Could not open database: open c:\bsc\chaindata\ancient\chain\headers.cidx: The system cannot find the file specified.`
> 
> Seems someone else is having the same problem [bnb-chain/bsc#2110 (comment)](https://github.com/bnb-chain/bsc/issues/2110#issue-2056511631)

colse, move to: https://github.com/bnb-chain/bsc/issues/2110
