### ISSUE TITLE
Missing blocks on BSC Erigon Archive Snapshot

### ISSUE THREAD

**Issue by gabronick** [bnb-chain/bsc-snapshots#334]
the snapshot based on files erigon_data_20240112.lz4.XXX has missing blocks 

example request, block 31167912: 

`{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1DB95A8",true],"id":1}`

Response:

`{"jsonrpc":"2.0","id":1,"result":null}`

example request, block 35167910

Response:

`{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "baseFeePerGas": "0x0",
        "difficulty": "0x2",
        "extraData": "0xd98301020f846765746889676f312e32302e3131856c696e7578000007b54328f8b5831dd7f7b860a0a0811ff105757943e21ada4b041b328b7872de20b76ee2131bb8ea7a975e71d48e12cf0615e9d9e3ee980baa1e85c409be6dc21a5dd79531d5f3f8f7a3726240f51e08611a8b5a6d8ae2ede2d336b25132320caf57d36b7e2735c4a28dda43f84c8402189ea4a0263ce031e4995f39d1d88daa66c7ac0f3042a43434c7a10078ea6902c0d391d08402189ea5a0340c0724074ef075fb6f6ca82e7e16197abcf34c3d1a988a1b3f6b22c220dbda80d6935ace634d310c86f750e1d4c582dc45be61e79da41185b7b67e41409bfbe41e54eee641d90f4e8f850f6760680df9dc938b6b14776b1e081bdc4c48bc3ac201",.....`
     (The answer has been shortened so that the text fits on the ticket)

**Comment by deepcrazy** [comment]
Hi there, What's your erigon version and startup command? And Can you share the logs too.

**Comment by gabronick** [comment]
Erigon v1.1.12

Startup command:

`erigon --sentry.drop-useless-peers --p2p.protocol=66 --txpool.disable --metrics.addr=0.0.0.0 --db.pagesize=16k --datadir /external/data --private.api.addr=localhost:9090 --chain=bsc --http.addr=0.0.0.0 --http.api=eth,debug,net,trace,web3,erigon --http.vhosts="*" --http.corsdomain="*" --metrics --torrent.download.rate=500mb --maxpeers 100 --nat any --downloader.verify `

There is nothing relevant in the logs, at first it starts downloading the snapshots, now it is running the synchronization, but there are missing blocks

log output

`INFO[01-26|05:59:06.236] logging to file system                   log dir=/external/data/logs file prefix=erigon log level=info json=false                                                    INFO[01-26|05:59:06.236] Starting metrics server                  addr=http://0.0.0.0:6060/debug/metrics/prometheus                                                                           INFO[01-26|05:59:06.245] Build info                               git_branch= git_tag= git_commit=                                                                                            INFO[01-26|05:59:06.245] Starting Erigon on BSC mainnet...                                                                                                                                    INFO[01-26|05:59:06.247] Maximum peer count                       ETH=100 total=100                                                                                                           INFO[01-26|05:59:06.248] starting HTTP APIs                       APIs=eth,debug,net,trace,web3,erigon                                                                                        INFO[01-26|05:59:06.248] torrent verbosity                        level=WRN                                                                                                                   INFO[01-26|05:59:08.353] Set global gas cap                       cap=50000000                                                                                                                INFO[01-26|05:59:08.359] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=500mb upload.rate=4mb                                                     INFO[01-26|05:59:08.359] Opening Database                         label=chaindata path=/external/data/chaindata                                                                               INFO[01-26|05:59:08.359] [db] params: growStep=2GB, mapsSize=10TB, shrinkThreshold=-1, pageSize=16KB, label=chaindata, WriteMap=false, Durable=false, NoReadahead=true,                       mdbx_setup_dxb:15946 filesize mismatch (expect 7817081831424b/477116811p, have 7825430413312b/477626368p)                                                                                     INFO[01-26|05:59:08.910] Initialised chain configuration          config="{ChainID: 56 Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Euler: 18907621, Gibbs: 23846001, Nano: 21962149, Moran: 22107423, Planck: 27281024, Luban: 29020050, Plato: 30720096, Hertz: 31302048, Hertzfix: 34140700, ShanghaiTime: 1705996800, KeplerTime 1705996800, Engine: parlia}" genesis=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b                                                                                                                             INFO[01-26|05:59:08.911] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v3=false                                                             INFO[01-26|05:59:17.506] Initialising Ethereum protocol           network=56                                                                                                                  INFO[01-26|05:59:19.487] Starting private RPC server              on=localhost:9090                                                                                                           INFO[01-26|05:59:19.487] new subscription to logs established                                                                                                                                 INFO[01-26|05:59:19.487] rpc filters: subscribing to Erigon events                                                                                                                            INFO[01-26|05:59:19.488] new subscription to newHeaders established                                                                                                                           INFO[01-26|05:59:19.488] Reading JWT secret                       path=/external/data/jwt.hex                                                                                                 INFO[01-26|05:59:19.489] HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true                                                                              INFO[01-26|05:59:19.489] HTTP endpoint opened                     url=[::]:8545 ws=false ws.compression=true grpc=false                                                                       INFO[01-26|05:59:19.492] Started P2P networking                   version=66 self=enode://443917cab07e715affccdd9dc6f4fe925e76d9675eb151300a5be38d782144ad6dc969c1f288804fc247dbca18a86b67e92148d0bb3a30261021ba2c360a36a2@127.0.0.1:0 name=erigon/v1.1.10/linux-arm64/go1.20.2                                                                                                             INFO[01-26|05:59:19.502] [1/15 Snapshots] Fetching torrent files metadata                                                                                                                     INFO[01-26|05:59:39.507] [snapshots] Verifying                    progress=9.48%
`

**Comment by zzzckck** [comment]
for erigon issue, better to track it in nodereal's repo: https://github.com/node-real/bsc-erigon

**Comment by gabronick** [comment]
@zzzckck what erigon are you using to make this snapshot? is not from node-real?

**Comment by gabronick** [comment]
@blxdyx 

`INFO[01-28|17:29:54.002] logging to file system                   log dir=data/logs file prefix=erigon log level=info json=false
INFO[01-28|17:29:57.722] [snapshots] Blocks Stat                  blocks=34000k indices=34000k alloc=2.4GB sys=2.6GB
Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

                                 stage_at        prune_at
Snapshots                        35645398        0
Headers                          35645399        0
BlockHashes                      35645399        0
Bodies                           35645399        0
Senders                          35645399        0
Execution                        35645399        35645399
Translation                      0               0
HashState                        35645399        0
IntermediateHashes               35645399        35645399
AccountHistoryIndex              35645399        0
StorageHistoryIndex              35645399        0
LogIndex                         35645399        0
CallTraces                       35645399        35645399
TxLookup                         35645399        35077000
Finish                           35645399        0
--
prune distance:

blocks.v2: blocks=33999999, segments=33999999, indices=33999999

history.v3: false, idx steps: 0.00, lastMaxTxNum=0->0, lastBlockInSnap=0

sequence: EthTx=5369256632, NonCanonicalTx=415413

in db: first header 35077000, last header 35645399, first body 35077000, last body 35645399`

**Comment by gabronick** [comment]
after running that command this message appeared:

 [1/15 Snapshots] Some blocks are not in snapshots and not in db max_in_snapshots=33999999 min_in_db=35077000

**Comment by zzzckck** [comment]
> @zzzckck what erigon are you using to make this snapshot? is not from node-real?

Yes, it is from nodereal.
