### ISSUE TITLE
Snapshot Size don't match with requirement of Minimum storage size 

### ISSUE THREAD

**Issue by supamongkonR** [bnb-chain/bsc-snapshots#340]
I've got a problem while extract snapshot file that I've download from this link in READ.MD 

``` 
mainnet: geth-pbss-pebble-20240115.tar.lz4
(https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240115.tar.lz4)
```
![image](https://github.com/bnb-chain/bsc-snapshots/assets/73258014/9d0873a3-d52c-4056-ad5f-9d2364f75b27)

it take around 2.3TB for snapshot file 
and include  /server folder(extracted file) take around 4.2TB, and it's seem like my instance in gonna be run out of storage space,

for documentation Full-node require 3TB minimum
https://docs.bnbchain.org/docs/validator/run-val/

,but I've got 4.8TB and it use right now 93% and extract process not done yet 
![image](https://github.com/bnb-chain/bsc-snapshots/assets/73258014/128e6d44-158c-4bb1-81d7-ef2b4dac91a2)

and I've seen in BNB48club that releases new snapshot version in https://github.com/48Club/bsc-snapshots, for snapshot fullnode the last 2 days version is getting around 676.89G <-> 748.31GB

my question is what difference between 

```
	https://snapshots.48.club/geth.full.36318889.tar.zst 
	// size 676.89G <-> 748.31GB
```
and 
```
      https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240115.tar.lz4
      // size 2.3TB
```

and which one that I should download, and what exactly storage size that I should using for BSC-full node.

**Comment by zzzckck** [comment]
https://snapshots.48.club/geth.full.36318889.tar.zst  ==> do historical blocks, only keep the most recent 90K blocks
https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240115.tar.lz4 ==> have full historical blocks
//===
you may choose depends on your need, if you don't need full historical blocks/receipts, you may use 48Club's as it is much smaller.

**Comment by zzzckck** [comment]
FYI: the latest historical blocks/receipt takes ~1.5TB
![image](https://github.com/bnb-chain/bsc-snapshots/assets/152148891/7fa9ae41-78b4-44e9-9b6c-4a860ea1e2b0)

**Comment by flywukong** [comment]
The snapshot should only require 2.3T after decompression. It is recommended that you use a temporary disk to store the snapshot file and decompress it to the disk directory where you run node (requires 3T). When the decompression is complete, you can delete the snapshot file.

**Comment by supamongkonR** [comment]
Thanks you so much.
