### ISSUE TITLE
Clarification of the snapshots

### ISSUE THREAD

**Issue by wtdcode** [bnb-chain/bsc-snapshots#348]
I'm trying to understand what these snapshots contain. Although there are already many discussions on this, I don't see a clarification or comparison and thus I'm trying to do it. My understanding of geth is limited so please correct me if anything is wrong.

=========

Some definitions:

- `state`: Contract state variables value
- `block`: Bodies, contains the properties of a transaction like `from`, `to`...
- `receipts`: Execution results and logs
- `header`: Properties of blocks, like `hash`, `number` ...

=========

Full node snapshots of this repo (2.4T roughly):

From #340

- `state`: Only recent 90k blocks
- `block`: Full chain
- `receipts`: Full chain
- `header`: Full chain

Full node snapshots of 48Club (800G roughly):

- `state`: Only recent 128 blocks. <---- Just confirmed with this. But with `--tries-verify-mode=none`, state beyond 128 blocks will return missing trie node.
- `block`: Only recent 90k blocks
- `receipts`: Only recent 90k blocks
- `header`: Only recent 90k blocks

Fast node snapshots of 48Club (200G roughly):

- `state`: Only recent 128 blocks. <----- I'm running a fast node indeed and find this. And most importantly, if the state is not available, RPC won't report an error and returns 0!
- `block`: Only recent 90k blocks
- `receipts`: Only recent 90k blocks
- `header`: Only recent 90k blocks

Erigon Snapshots (~8T):

- `state`: Full chain
- `block`: Full chain
- `receipts`: Full chain
- `header`: Full chain

Please clarify if these understand is correct.

=======

cc

@du5 
@zzzckck

**Comment by zzzckck** [comment]
Basically, you are right, I can update these clarification into the FAQ.

**Comment by wtdcode** [comment]
> Basically, you are right, I can update these clarification into the FAQ.

@zzzckck Which snapshot shall I use if I want to access more than 128 blocks live state?

**Comment by zzzckck** [comment]
> > Basically, you are right, I can update these clarification into the FAQ.
> 
> @zzzckck Which snapshot shall I use if I want to access more than 128 blocks live state? Or is that possible?

right now, I am afraid only Erigon archive node can support it, PBSS only keeps the most recent 128+1 state.

**Comment by zzzckck** [comment]
Include this issue in FAQ as the 1st question.
https://github.com/bnb-chain/bsc-snapshots/issues/349
@wtdcode pls check, if it answers your question.

**Comment by wtdcode** [comment]
Cool, thanks for the explanation. Will the hash-based scheme be deprecated finally?

**Comment by zzzckck** [comment]
> Cool, thanks for the explanation. Will the hash-based scheme be deprecated finally?

It is not determined yet, currently we just make sure hash-based function will not be broken, but in long run, if it could be deprecated if it needs too much effort to maintain it.
