### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by zzzckck** [bnb-chain/bsc-snapshots#349]
## Q1: Clarification of the snapshots
As [BSC will mainly support PBSS & PebbleDB](https://forum.bnbchain.org/t/faq-pbss-pebbledb/2260), we will only cover snapshots of PBSS&PebbleDB and ignore snapshot of HashBased&LevelDB here.
This Q&A is based on https://github.com/bnb-chain/bsc-snapshots/issues/348
Currently(2024-03-25) there are 3 different kinds of sources:
- **Source-1: Legacy Full Node(~2.4TB)**
Like this: https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240320.tar.lz4
`state`: Only recent 90K blocks, but only the state of the most recent 129(128+1) blocks can be queried through RPC "eth.getStorageAt(...)". The older states are only used for big reorg, which is part of the PBSS design.
`block`: Full chain
`receipts`: Full chain
`header`: Full chain

- **Source-2: FullNode(~900GB) & FastNode(~200GB) By 48Club**
[About BSC FastNode](https://github.com/bnb-chain/bsc/releases/tag/v1.1.12)
Currently, 48Club provides 2 kinds of snapshot which require less disk volume, as they only save the recent 90K blocks/receipts/headers. And for the 2 kinds of snapshot: 1 is full node with trie node, the other is fast node without trie node.
**48Club FullNode(~900GB):**
`state`: Only recent 129 blocks. <---- Just confirmed with this. But with --tries-verify-mode=none, state beyond 129 blocks will return missing trie node.
`block`: Only recent 90k blocks
`receipts`: Only recent 90k blocks
`header`: Only recent 90k blocks
**48Club FastNode(~200GB):**
`state`: Only recent 129 blocks. <----- I'm running a fast node indeed and find this. And most importantly, if the state is not available, RPC won't report an error and returns 0!
`block`: Only recent 90k blocks
`receipts`: Only recent 90k blocks
`header`: Only recent 90k blocks

- **Source-3: Erigon Archive Node(~8TB)**
BSC Erigon is maintained by NodeReal in repo: https://github.com/node-real/bsc-erigon/, right now it is the only runnable archive node for BSC.
`state`: Full chain
`block`: Full chain
`receipts`: Full chain
`header`: Full chain

## Q2: How To Get Hash Based Snapshot
> Please be advised that support for the Hash&LevelDB mode will be discontinued after September 30, 2024. Consequently, the functionality may become unavailable or cease to function properly at any time following this date.
Hash based snapshot has been replaced by PBSS.

The last update for mainnet is on 2024-03-20, check: https://github.com/bnb-chain/bsc-snapshots/pull/345/files
The last update for Testnet is on 2024-03-21, check: https://github.com/bnb-chain/bsc-snapshots/pull/346/files
The download links are not guaranteed and could be broken in the future.

**Comment by zhk101** [comment]
> * **48Club FastNode(~200GB):**
>       `state`: Only recent 129 blocks. <----- I'm running a fast node indeed and find this. And most importantly, if the state is not available, RPC won't report an error and returns 0!
>       `block`: Only recent 90k blocks
>       `receipts`: Only recent 90k blocks
>       `header`: Only recent 90k blocks

Will this still be the case once 48Club will switch to PBSS, specifically for `block`/`receipts`/`header`? I read somewhere that PBSS holds less state but I might be confusing with `state` only

**Comment by zzzckck** [comment]
> > * **48Club FastNode(~200GB):**
> >   `state`: Only recent 129 blocks. <----- I'm running a fast node indeed and find this. And most importantly, if the state is not available, RPC won't report an error and returns 0!
> >   `block`: Only recent 90k blocks
> >   `receipts`: Only recent 90k blocks
> >   `header`: Only recent 90k blocks
> 
> I assumes these number applies to the current fastnode snapshot which is not using PBSS. Will this still be the case once they'll switch to PBSS, specifically for `block`/`receipts`/`header`? I read somewhere that PBSS holds less state but this might affect only the `state`?

It will still be the case for FastNode-PBSS, since FastNode will not contain trie node, which means it is irrelevant to PBSS or HashBased, as it will not keep the trie node.
