### ISSUE TITLE
Snapshot download with Endpoint(Mainnet torrent,the block range[0, 36,500,000))

### ISSUE THREAD

**Issue by shivraj001** [bnb-chain/bsc-snapshots#353]
We have downloaded the snapshot [**erigon_snapshots_20240301.tar.lz4**](https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_snapshots_20240301.tar.lz4/erigon_snapshots_20240301.tar.lz4) md5=04238a8fb079904f4f1c8a9862054d7e  

There isn't enough information to use this file erigon_snapshots_20240301.tar.lz4 to run erigon client.

Does moving the mdx.dat (cat "erigon_data_20240416"* > mdbx.dat) to chaindata folder file is enough? or we need to move the torrent snapshot erigon_snapshots_20240301.tar.lz4 as well?

**Comment by zlacfzy** [comment]
The torrent snapshot should move to the datadir/snapshots
 The mdbx.dat should mv to datadir/chaindata folder

**Comment by zzzckck** [comment]
the `torrent snapshot` download file is no longer supported. so close this issue.
