### ISSUE TITLE
no torrent any more?

### ISSUE THREAD

**Issue by zfy0701** [bnb-chain/bsc-snapshots#359]
see this pr delete it

https://github.com/bnb-chain/bsc-snapshots/commit/0681de1321b410741cada5c4e482546937be2f7b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L158-L161

**Comment by 0xdefo** [comment]
> yes, because usually snapshots is not match the chaindata. So most time need `integration stages_header --reset` when start. So now it will use bittorrent to download the snapshots.

If the datadir/snapshots folder and the datadir/chaindata folder are packaged and published at the same time, should they match?
