### ISSUE TITLE
Erigon: Hi, I got this error when running the archive node

### ISSUE THREAD

**Issue by keienWang** [bnb-chain/bsc-snapshots#366]
<img width="1130" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/42377006/9a05cc9e-ef2b-47af-ab5a-7a0b4fce7472">

1. Downloaded all snapshot data and exported it as mdbx.dat
2. Replace the mdbx.dat in the previous chaindata directory with the mdbx.dat
3. ./erigon --chain=bsc --datadir /data/bscdata/

ubuntu 22:04
32 RAM
8T SSD

**Comment by zlacfzy** [comment]
Have you check the checksum?

**Comment by dedsxc** [comment]
The procedure to unzip the compressed snapshot seems wrong on the readme. What it works for me so far: 

```
cat $(seq -f "erigon_data_$SNAPSHOT_VERSION.lz4.%03g" 0 7) > erigon_data.lz4
lz4 -qd -c erigon_data.lz4 > $CONFIG_DIR/chaindata/mdbx.dat
```

**Comment by zlacfzy** [comment]
> The procedure to unzip the compressed snapshot seems wrong on the readme. What it works for me so far:
> 
> ```
> cat $(seq -f "erigon_data_$SNAPSHOT_VERSION.lz4.%03g" 0 7) > erigon_data.lz4
> lz4 -qd -c erigon_data.lz4 > $CONFIG_DIR/chaindata/mdbx.dat
> ```

The latest version works too?  Actually we change the way just spilt the db before compress it. So just need decompress and    then cat to a mdbx file.

**Comment by testbugsec2022** [comment]
The decompression failed and the file does not exist. However, the file does exist. I don’t understand why. Can you explain it?
![Uploading WX20240703-221838.png…]()

**Comment by testbugsec2022** [comment]
> > The procedure to unzip the compressed snapshot seems wrong on the readme. What it works for me so far:
> > ```
> > cat $(seq -f "erigon_data_$SNAPSHOT_VERSION.lz4.%03g" 0 7) > erigon_data.lz4
> > lz4 -qd -c erigon_data.lz4 > $CONFIG_DIR/chaindata/mdbx.dat
> > ```
> 
> The latest version works too? Actually we change the way just spilt the db before compress it. So just need decompress and then cat to a mdbx file.

I am using version 0520. Is there something wrong with this version? The md5 values ​​are all verified and there is no problem.

**Comment by testbugsec2022** [comment]
5983392858e54bf40e05853294399303  erigon_data_20240520.lz4.000
14ac48c4f866c6f754ac3a2c661d6eb4  erigon_data_20240520.lz4.001
9cd5075e8e611a35c44eec3cd31305f0  erigon_data_20240520.lz4.004
c7c95f96200d35b81e52d50f8ed52ebf  erigon_data_20240520.lz4.002
2f2d918363c992bb9254dd6504d8a541  erigon_data_20240520.lz4.003
0bd256afaf42bfb4b163354142cfda0d  erigon_data_20240520.lz4.005
4f31de846555841326fa04ccd00b5b67  erigon_data_20240520.lz4.006
e2750053a2656b6cbaf743459480c144  erigon_data_20240520.lz4.007

**Comment by zlacfzy** [comment]
> 5983392858e54bf40e05853294399303 erigon_data_20240520.lz4.000 14ac48c4f866c6f754ac3a2c661d6eb4 erigon_data_20240520.lz4.001 9cd5075e8e611a35c44eec3cd31305f0 erigon_data_20240520.lz4.004 c7c95f96200d35b81e52d50f8ed52ebf erigon_data_20240520.lz4.002 2f2d918363c992bb9254dd6504d8a541 erigon_data_20240520.lz4.003 0bd256afaf42bfb4b163354142cfda0d erigon_data_20240520.lz4.005 4f31de846555841326fa04ccd00b5b67 erigon_data_20240520.lz4.006 e2750053a2656b6cbaf743459480c144 erigon_data_20240520.lz4.007

Try this:
```
lz4 -d erigon_data_20240520.lz4.[0]..erigon_data_20240520.lz4.[7]
cat "erigon_data_20240520"* > mdbx.dat
```

**Comment by testbugsec2022** [comment]
> lz4 -d erigon_data_20240520.lz4.[0]..erigon_data_20240520.lz4.[7]

root@bscnode:/data2/bscsnap# /usr/bin/lz4 -d erigon_data_20240520.lz4.[0]..erigon_data_20240520.lz4.[7]
erigon_data_20240520.lz4.[0]..erigon_data_20240520.lz4.[7]: is not a regular file

**Comment by testbugsec2022** [comment]
> > > lz4 -d erigon_data_20240520.lz4.[0]..erigon_data_20240520.lz4.[7]
> > 
> > 
> > root@bscnode:/data2/bscsnap# /usr/bin/lz4 -d erigon_data_20240520.lz4.[0]..erigon_data_20240520.lz4.[7] erigon_data_20240520.lz4.[0]..erigon_data_20240520.lz4.[7]: is not a regular file
> 
> You need do that one by one. `lz4 -d erigon_data_20240520.lz4.000 and then lz4 -d erigon_data_20240520.lz4.001 `

Thank you 
Please provide the md5sum of mdbx.dat of 0520. Thanks

**Comment by zlacfzy** [comment]
`31fdebebe89ab25bf5842fa2055428a14281c8279ce2499eef93fece5a94deea`
