### ISSUE TITLE
Setup bittorrent seed to accelerate download speed

### ISSUE THREAD

**Issue by nining** [bnb-chain/bsc-snapshots#37]
BitTorrent is a peer-to-peer download network that sometimes enables higher download speeds and more reliable downloads of large files.  Let the peers contribute bandwidth !

Here is how to setup a BitTorrent tracker and share file:
[How to use qBittorrent as a tracker
](https://github.com/qbittorrent/qBittorrent/wiki/How-to-use-qBittorrent-as-a-tracker)

**Comment by guagualvcha** [comment]
The dev is working on this
