### ISSUE TITLE
Erigon: Node out-of-sync problem

### ISSUE THREAD

**Issue by keienWang** [bnb-chain/bsc-snapshots#373]
#### Command
<img width="1096" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/42377006/f09fad1f-7d73-4945-8097-580ba5ac993b">

The node was started successfully, but one is out of sync, started based on the snapshot on May 20

 #### log
<img width="1082" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/42377006/97218a88-616f-4517-8b9e-201b76d83898">

ubuntu 22:04
32 RAM
15T Mechanical hard disk

**Comment by STdevK** [comment]
Try syncing with the latest Erigon snapshot

**Comment by keienWang** [comment]
I think I didn't start the downloader. Do I need to start the downloader to download the Chinese file? I think the documentation for snapshot startup should be more comprehensive. Thank you.

**Comment by zlacfzy** [comment]
https://github.com/node-real/bsc-erigon/releases/tag/v1.2.13
https://github.com/node-real/bsc-erigon/issues/441
