### ISSUE TITLE
Fullnode testnet not sync

### ISSUE THREAD

**Issue by Kidkender** [bnb-chain/bsc-snapshots#374]
I've been running this full node for 3 days, but now it's height is quite slow.
**This is cli start:**
node@fullnodes:~/binance$ ./geth --config ./config.toml --datadir ./node  --cache 20000 --rpc.allow-unprotected-txs --history.transactions 0 --syncmode snap --port 30334

retrieve current node:
{
  currentBlock: 40760939,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 41981495,
  startingBlock: 40760808,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,                                                                                                                                                                         syncedStorage: 0,
  syncedStorageBytes: 0,
  txIndexFinishedBlocks: 40760810,
  txIndexRemainingBlocks: 0
}

on geth screen I don't see the sync percentage progress bar
![image](https://github.com/bnb-chain/bsc-snapshots/assets/84608369/2581178b-0060-43b5-864d-91df41782883)

My Server:
- RAM: 256GB
- SSD: 2TB

**Comment by STdevK** [comment]
which testnet snapshot did you use?

**Comment by zzzckck** [comment]
> I've been running this full node for 3 days, but now it's height is quite slow. **This is cli start:** node@fullnodes:~/binance$ ./geth --config ./config.toml --datadir ./node --cache 20000 --rpc.allow-unprotected-txs --history.transactions 0 --syncmode snap --port 30334
> 
> retrieve current node: { currentBlock: 40760939, healedBytecodeBytes: 0, healedBytecodes: 0, healedTrienodeBytes: 0, healedTrienodes: 0, healingBytecode: 0, healingTrienodes: 0, highestBlock: 41981495, startingBlock: 40760808, syncedAccountBytes: 0, syncedAccounts: 0, syncedBytecodeBytes: 0, syncedBytecodes: 0, syncedStorage: 0, syncedStorageBytes: 0, txIndexFinishedBlocks: 40760810, txIndexRemainingBlocks: 0 }
> 
> on geth screen I don't see the sync percentage progress bar ![image](https://private-user-images.githubusercontent.com/84608369/347658626-2581178b-0060-43b5-864d-91df41782883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODA3NjAsIm5iZiI6MTcyMDY4MDQ2MCwicGF0aCI6Ii84NDYwODM2OS8zNDc2NTg2MjYtMjU4MTE3OGItMDA2MC00M2I1LTg2NGQtOTFkZjQxNzgyODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA2NDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYjFiMjI1NTRhYTAyMmUwMTIxZWQwMTMxN2VkNzFkODFkYTM5Nzk0MjM3MmYyODgwNWE4NTk4NDBjMzY5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cq8akaycjM4NzK1mAwTWYniHSY0tRewzs3iFE_bOkVY)
> 
> My Server:
> 
> * RAM: 256GB
> * SSD: 2TB

The latest testnet snapshot is broken, we will upgrade a new one

**Comment by zzzckck** [comment]
pls use the latest testnet snapshot
