### ISSUE TITLE
Issue:After moving mdbx.dat in chain data directory ,dictionary is corrupted

### ISSUE THREAD

**Issue by sowjanya-vangeti** [bnb-chain/bsc-snapshots#378]
I have used erigon version v1.2.10
Below are the steps I have followed 

1. ./erigon --datadir /datadisk/node/erigon-start   
2.  killed ( running the process )
3. mv /datadisk/node/erigon-start/chaindata/mdbx.dat /datadisk/node/erigon-start/chaindata/mdbx.dat.bkp
4. mv /datadisk/node/bsc-snapshots/mdbx.dat /datadisk/node/erigon-start/chaindata/mdbx.dat
5. ./erigon --txpool.disable --metrics.addr=0.0.0.0 --log.console.verbosity=dbug --db.pagesize=16k --datadir /datadisk/node/erigon-start --private.api.addr=localhost:9090 --chain=bsc --metrics --log.dir.path /datadisk/node/erigon-start/logs

After running these steps i could see below error and also Torrent Directory snapshot is missing in README

WARN[07-29|12:47:53.246] [snapshots] open segment                 err="compressed file \"v1-038400-038500-headers.seg\" dictionary is corrupted: size 62.8 MB but no words in it, fileName: v1-038400-038500-headers.seg"

![Screenshot from 2024-07-29 18-35-48](https://github.com/user-attachments/assets/9141b5d1-ee4a-44c5-a77f-bad95de0d47e)
hments/assets/322213c8-e9fc-45e6-88fb-bd4e981376a4)

**Comment by zlacfzy** [comment]
1. remove the datadir/downloader
2. cd data/snapshots && rm -rf *idx.
3. than restart

**Comment by tardigralice** [comment]
i had same issue.
i tried to remove downloader folder and   rm -rf *idx in the snapshot folder.

but issue is still there when i restart.

however, i have an INFO saying it's adding torrent.

```tions.seg\" dictionary is corrupted: size 2.2 GB but no words in it, fileName: v1-040600-040700-transactions.seg"
Aug 09 12:09:22 Ubuntu-2204-jammy-amd64-base bash[2402515]: [WARN] [08-09|12:09:22.785] [snapshots] open segment                 err="compressed file \"v1-040700-040800-bodies.seg\" dictionary is corrupted: size 1.1 MB but no words in it, fileName: v1-040700-040800-bodies.seg"
Aug 09 12:09:22 Ubuntu-2204-jammy-amd64-base bash[2402515]: [WARN] [08-09|12:09:22.785] [snapshots] open segment                 err="compressed file \"v1-040700-040800-headers.seg\" dictionary is corrupted: size 62.1 MB but no words in it, fileName: v1-040700-040800-headers.seg"
Aug 09 12:10:02 Ubuntu-2204-jammy-amd64-base bash[2402515]: [INFO] [08-09|12:10:02.936] [snapshots] Adding .torrent files        progress=68/301
Aug 09 12:10:23 Ubuntu-2204-jammy-amd64-base bash[2402515]: [INFO] [08-09|12:10:23.730] [snapshots] Adding .torrent files        progress=91/301
```

**Comment by zlacfzy** [comment]
Make sure you use the latest release?

**Comment by bigjoker007** [comment]
> Make sure you use the latest release?

The latest version 1.2.15 also has this issue.
