### ISSUE TITLE
Missing blocks in latest snapshot

### ISSUE THREAD

**Issue by JB273** [bnb-chain/bsc-snapshots#380]
I have downloaded the latest snapshot for mainnet BSC and it seems it is at least missing the following blocks:
Missing block range: 35000000 to 35127295 (0x2160EC0 to 0x217FFFF)

Tested this with a script that checks a range of blocks if the return value = `null`!

**Comment by zzzckck** [comment]
checking

**Comment by NathanBSC** [comment]
I use [geth-pbss-pebble-20240802.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240802.tar.lz4) 
and can get blocks via console,
![image](https://github.com/user-attachments/assets/957788e4-3436-42ff-a0c0-b8f7d8b5f00c)
![image](https://github.com/user-attachments/assets/4519d809-2a5d-4d97-bb16-88e7d0724b2e)
@JB273 
can you show you script?

**Comment by JB273** [comment]
Sure (please note I'm querying the endpoint, in case of the script just local):
`#!/bin/bash

# Define start and end blocks in hex
start_block_hex="0x2130000"
end_block_hex="0x214ffff"

# Convert hex to decimal
start_block_dec=$((start_block_hex))
end_block_dec=$((end_block_hex))

# Array to hold missing blocks
declare -a missing_blocks

# Loop from start block to end block
for ((block=$start_block_dec; block<=$end_block_dec; block++))
do
    # Convert the block number back to hex for the query
    block_hex=$(printf "0x%X" $block)

    # Perform the query
    response=$(curl -s http://127.0.0.1:8545 -X POST -H "Content-Type: application/json" --data "{\"method\":\"eth_getBlockByNumber\",\"params\":[\"$block_hex\",false],\"id\":1,\"jsonrpc\":\"2.0\"}")

    # Check if the block is missing or returning data
    if echo "$response" | grep -q '"result":null'; then
        # Add the block to the missing blocks array
        missing_blocks+=($block)
    fi
done

# Function to print ranges of missing blocks
print_missing_ranges() {
    local -n blocks=$1
    local range_start=""
    local range_end=""

    for ((i=0; i<${#blocks[@]}; i++)); do
        if [[ -z $range_start ]]; then
            range_start=${blocks[$i]}
            range_end=${blocks[$i]}
        elif [[ ${blocks[$i]} -eq $((range_end + 1)) ]]; then
            range_end=${blocks[$i]}
        else
            echo "Missing block range: $range_start to $range_end"
            range_start=${blocks[$i]}
            range_end=${blocks[$i]}
        fi
    done
    # Print the last range if exists
    if [[ -n $range_start ]]; then
        echo "Missing block range: $range_start to $range_end"
    fi
}

# Call function to print missing ranges
print_missing_ranges missing_blocks
`

**Comment by JB273** [comment]
> I use [geth-pbss-pebble-20240802.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240802.tar.lz4) and can get blocks via console, ![image](https://private-user-images.githubusercontent.com/122502194/356123160-957788e4-3436-42ff-a0c0-b8f7d8b5f00c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDQ0NDgsIm5iZiI6MTcyMzEwNDE0OCwicGF0aCI6Ii8xMjI1MDIxOTQvMzU2MTIzMTYwLTk1Nzc4OGU0LTM0MzYtNDJmZi1hMGMwLWI4ZjdkOGI1ZjAwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwODAyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTE2ZWFhMjU4NTA1ZWE1ZGRmYWRiNzM1MGVjNWVhNjUyN2E2Njc5YzhiYzYxMzA1ZGEyNGE2ZGVlNjFmMjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6vn8EBEqbsMUvrBEBZrOJeHiG3_O4S2yRtfURrssrk4) ![image](https://private-user-images.githubusercontent.com/122502194/356123382-4519d809-2a5d-4d97-bb16-88e7d0724b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDQ0NDgsIm5iZiI6MTcyMzEwNDE0OCwicGF0aCI6Ii8xMjI1MDIxOTQvMzU2MTIzMzgyLTQ1MTlkODA5LTJhNWQtNGQ5Ny1iYjE2LTg4ZTdkMDcyNGIyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwODAyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjJmNmMyZTE5YTRkNjE5ZGFiOGIxMDQ4ODg3NzYxYzk0MTQ1YjZhMzQ4NTAxNjQ3ZDFlMDY2NTk5ZTJlOGVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5NnyaQJzj3t2B2j5v1wQEse22tH0CZpb9-Za1F5f7jc) @JB273 can you show you script?

Please also note I was using the snapshot before the current latest!
I see you're currently using latest august snapshots

**Comment by NathanBSC** [comment]
can you try  just get one block?
```
curl https://docs-demo.quiknode.pro/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getBlockByNumber","params":["0x217ffff",false],"id":1,"jsonrpc":"2.0"}'
```

you may be blocked by rpc limit when you use script

**Comment by JB273** [comment]
> can you try just get one block?
> 
> ```
> curl https://docs-demo.quiknode.pro/ \
>   -X POST \
>   -H "Content-Type: application/json" \
>   --data '{"method":"eth_getBlockByNumber","params":["0x217ffff",false],"id":1,"jsonrpc":"2.0"}'
> ```
> 
> you may be blocked by rpc limit when you use script

I'm for sure not rate limited as I'm doing it against our localhost with no limits, but also tried multiple of these already manually (one by one), I just used the script to see what blocks were missing actually on our RPC.

**Comment by JB273** [comment]
Request:
`curl http://localhost:8546/   -X POST   -H "Content-Type: application/json"   --data '{"method":"eth_getBlockByNumber","params":["0x217ffff",false],"id":1,"jsonrpc":"2.0"}'`
Result
`{"jsonrpc":"2.0","id":1,"result":null}`

**Comment by NathanBSC** [comment]
> [geth-pbss-pebble-20240802.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240802.tar.lz4)

thx, pls use [geth-pbss-pebble-20240802.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240802.tar.lz4)
if issue still exists, report here.

**Comment by JB273** [comment]
> > [geth-pbss-pebble-20240802.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240802.tar.lz4)
> 
> thx, pls use [geth-pbss-pebble-20240802.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240802.tar.lz4) if issue still exists, report here.

We are using erigon with archive... so not sure that will help us any further

**Comment by NathanBSC** [comment]
> > > [geth-pbss-pebble-20240802.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240802.tar.lz4)
> > 
> > 
> > thx, pls use [geth-pbss-pebble-20240802.tar.lz4](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240802.tar.lz4) if issue still exists, report here.
> 
> We are using erigon with archive... so not sure that will help us any further

can you provide the data link you are using?
I thought you were using a snapshot of bsc geth...

**Comment by zlacfzy** [comment]
For erigon node. It will miss node if have gap between history block(data/snapshots) and mdbx. One way to fix that is use the latest release, and reset the headers.

**Comment by zlacfzy** [comment]
Refer this: https://github.com/bnb-chain/bsc-snapshots/blob/main/usage/erigon_archivenode_usage.md#missing-blocks
