### ISSUE TITLE
Snaphshot uri errorCode=3 Resource not found

### ISSUE THREAD

**Issue by breezytm** [bnb-chain/bsc-snapshots#393]
The archival node snapshot doesn't appear to be working.

```
aria2c -s14 -x14 -k100M https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240625.lz4.[0]..erigon_data_20240625.lz4.[7]

10/27 02:15:33 [NOTICE] Downloading 1 item(s)

10/27 02:15:34 [ERROR] CUID#7 - Download aborted. URI=https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240625.lz4.[0]..erigon_data_20240625.lz4.[7]
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240625.lz4.[0]..erigon_data_20240625.lz4.[7]
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found
[#ca6df4 0B/0B CN:0 DL:0B]
10/27 02:15:35 [NOTICE] Download GID#ca6df40949a65f44 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
ca6df4|ERR |       0B/s|https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240625.lz4.[0]..erigon_data_20240625.lz4.[7]

Status Legend:
(ERR):error occurred.
```

**Comment by zzzckck** [comment]
erigon_data_20240625? I am afraid it is expired.

**Comment by JPaikkari7** [comment]
https://github.com/bnb-chain/bsc-snapshots/issues/393 https://www.bing.com/saves?type=videos&FORM=SAVEVI&collId=6344aa2f825d47cfac23aa7900184d74[]()https://app.uniswap.org/swap?outputcurrency=0x93eb0b6f1d2fa434fca5cde0699f5dbe578f3879&chain=ethereum&utm_source=dexscreener&utm_medium=appSynkronointi🌐: https://deluge.cash

🕊: https://twitter.com/DelugeCash

💬: https://t.me/delugecashchat🌐: https://deluge.cash

🕊: https://twitter.com/DelugeCash

💬: https://t.me/delugecashchat@DelugeCashDisclaimer: @DelugeCash or any channel/bot associated with @DelugeCash or the dl.cash or deluge.cash brand, including channels with "trending tokens" ("we", "us", or "our") does not give you any financial advice, they are created for informational and educational purposes only, about what is happening in crypto. Investing in cryptocurrency always carries high risks. Much of the information and tokens we provide are paid advertisements for which we receive a fee or commission and this may affect all information. Another part of the information appears based on a certain algorithm, which may change. Although our marketing system and algorithms try to keep unsafe tokens out, no system is perfect, so always be cautious and vigilant with all information! We do not guarantee the reliability or security of the information provided. Always consult a qualified professional before deciding to purchase anything! By using our services and information, you agree to indemnify and hold us harmless from any and all claims arising out of your use of our services or information. This disclaimer is subject to change.deluge.cashdeluge.cash /TRX/40d832d14cd3eb2c7cdc006f59f46f9ce09d59d2570519eb2652bbe93c0759c1Check out this site! https://app.uniswap.org/swap?outputcurrency=0x93eb0b6f1d2fa434fca5cde0699f5dbe578f3879&chain=ethereum&utm_source=dexscreener&utm_medium=apphttps://fedtradecommission.gov1.qualtrics.com/jfe/form/SV_6ydaYuqrSwZXgSa?Q_CHL=sihttps://fedtradecommission.gov1.qualtrics.com/jfe/form/SV_6ydaYuqrSwZXgSa?Q_CHL=sihttps://fedtradecommission.gov1.qualtrics.com/jfe/form/SV_6ydaYuqrSwZXgSa?Q_CHL=sihttps://tx.botdev.me/TRX/40d832d14cd3eb2c7cdc006f59f46f9ce09d59d2570519eb2652bbe93c0759c1@Tamago_OFFICIAL_PLATINUMv3bot hhtps://fedtradecomission.gov1.qualtrics.com/jfe/form/SV_6ydaYuqrSwZXgSa?Q_CHL=si@Tamago_OFFICIAL_PLATINUMv3bothttps://fedtradecommission.gov1.qualtrics.com/jfe/form/SV_6ydaYuqrSwZXgSa?Q_CHL=si@Tamago_OFFICIAL_PLATINUMv3bothttps://tx.botdev.me/TRX/40d832d14cd3eb2c7cdc006f59f46f9ce09d59d2570519eb2652bbe93c0759c1/TRX/40d832d14cd3eb2c7cdc006f59f46f9ce09d59d2570519eb2652bbe93c0759c1/TRX/40d832d14cd3eb2c7cdDisclaimer: @DelugeCash or any channel/bot associated with @DelugeCash or the dl.cash or deluge.cash brand, including channels with "trending tokens" ("we", "us", or "our") does not give you any financial advice, they are created for informational and educational purposes only, about what is happening in crypto. Investing in cryptocurrency always carries high risks. Much of the information and tokens we provide are paid advertisements for which we receive a fee or commission and this may affect all information. Another part of the information appears based on a certain algorithm, which may change. Although our marketing system and algorithms try to keep unsafe tokens out, no system is perfect, so always be cautious and vigilant with all information! We do not guarantee the reliability or security of the information provided. Always consult a qualified professional before deciding to purchase anything! By using our services and information, you agree to indemnify and hold us harmless from any and all claims arising out of your use of our services or information. This disclaimer is subject to change./TRX/40d832d14cd3eb2c7cdc006f59f46f9ce09d59d2570519eb2652bbe93c0759c1Check out this site! https://app.uniswap.org/swap?outputcurrency=0x93eb0b6f1d2fa434fca5cde0699f5dbe578f3879&chain=ethereum&utm_source=dexscreener&utm_medium=apphttps://fedtradecommission.gov1.qualtrics.com/jfe/form/SV_6ydaYuqrSwZXgSa?Q_CHL=sihttps://fedtradecommission.gov1.qualtrics.com/jfe/form/SV_6ydaYuqrSwZXgSa?Q_CHL=sihttps://fedtradecommission.gov1.qualtrics.com/jfe/form/SV_6ydaYuqrSwZXgSa?Q_CHL=sihttps://tx.botdev.me/TRX/40d832d14cd3eb2c7cdc006f59f46f9ce09d59d2570519eb2652bbe93c0759c1@Tamago_OFFICIAL_PLATINUMv3bot hhtps://fedtradecomission.gov1.qualtrics.com/jfe/form/SV_6ydaYuqrSwZXgSa?Q_CHL=si@Tamago_OFFICIAL_PLATINUMv3bothttps://fedtradecommission.gov1.qualtrics.com/jfe/form/SV_6ydaYuqrSwZXgSa?Q_CHL=si@Tamago_OFFICIAL_PLATINUMv3bothttps://tx.botdev.me/TRX/40d832d14cd3eb2c7cdc006f59f46f9ce09d59d2570519eb2652bbe93c0759c1/TRX/40d832d14cd3eb2c7cdc006f59f46f9ce09d59d2570519eb2652bbe93c0759c1/TRX/40d832d14cd3eb2c7cd
