### ISSUE TITLE
Monthly snapshot is 3 month old

### ISSUE THREAD

**Issue by kaber2** [bnb-chain/bsc-snapshots#394]
The full node snapshot hasn't been updated for three months. Could you upload a new version?

**Comment by STdevK** [comment]
currently preparing the latest snapshot, please wait

**Comment by zzzckck** [comment]
@kaber2 updated the BSC full node snapshot. But if you refer to the Erigon snapshot, it will be replaced by Erigon 3, which don't need a snapshot any more.

**Comment by kaber2** [comment]
I was referring to the standard geth snapshot. Thank you very much.

**Comment by zzzckck** [comment]
ok, updated, close this issue, will update the md5 later
