### ISSUE TITLE
Deploy the archive node，an error log on starting

### ISSUE THREAD

**Issue by EWIT521** [bnb-chain/bsc-snapshots#396]
error message:
“migrator.VerifyVersion: cannot switch major DB version, db: 6, erigon: 7, try "rm -rf /data/bnbdata"
Snapshot data when it was most recently downloaded

**Comment by STdevK** [comment]
Are you using erigon_data_20240803? Can you share the node start-up command?

**Comment by EWIT521** [comment]
yes (erigon_data_20240803)
The file is normal,the path to the store is "/data/erigon/chaindata/mdbx.dat" 
start-up command:
erigon  --chain=bsc  --txpool.disable --http.addr=[0.0.0.0](http://0.0.0.0/) --http.port=7001 --metrics.addr=[0.0.0.0](http://0.0.0.0/) --log.console.verbosity=dbug --db.pagesize=16k --datadir="/data/erigon" --private.api.addr=localhost:9090 --chain=bsc --metrics --log.dir.path="/data/logs"
![img_v3_02g3_df61616a-b948-4bae-9b16-0bd9cdcf135h](https://github.com/user-attachments/assets/9ef3a876-a351-446f-ba52-6305ae0478cf)

**Comment by EWIT521** [comment]
![img_v3_02g3_adef0b49-9337-4c5b-a964-da893236106h](https://github.com/user-attachments/assets/7d66f756-5a00-4a9f-ae72-eb64c7b06b45)

**Comment by zlacfzy** [comment]
Make sure your version is `ghcr.io/node-real/bsc-erigon:1.2.16`
