### ISSUE TITLE
Snap sync VERY slow. 🐌 🐌 🐌

### ISSUE THREAD

**Issue by mcoelho80** [bnb-chain/bsc-snapshots#43]
I've downloaded last snapshot, but sync is VERY slow.

t=2021-11-05T18:14:30-0300 lvl=info msg="Imported new chain segment"          blocks=5  txs=2426 mgas=395.531 elapsed=8.935s    mgasps=44.263 number=12,251,260 hash=0x78cefacb792348786ec1a2263d813a77c7d961be8683ae4107829dfb4542190f age=5d6h25m  dirty="1.02 GiB"

I'm using a NVME 4Tb disk and snapshot sync mode.

 Is there any way to speed up synchronization?

**Comment by masayil** [comment]
It seems that we have almost nothing to do.
It contains too many transactions in one block .

**Comment by masayil** [comment]
I run some archive nodes.His synchronization speed is  a nightmare

**Comment by guagualvcha** [comment]
The speed is `44.263`, which is expected.
