### ISSUE TITLE
err="the method miner_start does not exist/is not available"

### ISSUE THREAD

**Issue by tropo76** [bnb-chain/bsc-snapshots#46]
Hello
i am syncing with 1.1.3 and the snapshot from here.
i'm not miner or validator. just full node.
i am still in sync process, and got only 3 block max /seconds ( AX61 NVME gen4)
i got lots of error like this:

err="the method miner_start does not exist/is not available"
and also:
lvl=eror msg="diff layers too new from current"

any idea why ?
thanks !

**Comment by masayil** [comment]
err="the method miner_start does not exist/is not available" means that someone request an api that you did not enable .
lvl=eror msg="diff layers too new from current" . I also have this problem, but I have not found any impact on the node due to this error.

**Comment by zigg76** [comment]
thanks for your answer.
