### ISSUE TITLE
Snapshot not syncing?

### ISSUE THREAD

**Issue by gry** [bnb-chain/bsc-snapshots#49]
Hi, I downloaded the latest snapshot,  geth 1.1.4, and the config.toml for the release 1.1.4 for mainnet, and following the docs it seems to get stuck without doing nothing.

I renamed the original "server" name to node in the same folder where the geth executable is, and run the following:

~~~
./geth_1.1.4 --config mainnet_1.1.3/config.toml --syncmode snap --datadir ./node --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0
INFO [11-08|09:42:42.660] Starting Geth on Ethereum mainnet...                                                                                                       
INFO [11-08|09:42:42.663] Maximum peer count                       ETH=30 LES=0 total=30                                                                             
INFO [11-08|09:42:42.663] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"                                       
WARN [11-08|09:42:42.663] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
~~~

(And then there is silence)

Can someone help me to understand what is wrong in this setup?

Thank you!

**Comment by Undead8** [comment]
add the flag `--verbosity 3` . You should see some entries about new blocks being downloaded while it's syncing.

**Comment by SnakePin** [comment]
You probably aren't seeing anything on the console because if you're using the `config.toml` that is supplied with the `mainnet.zip`, your config file is set to log to a file instead of the console. Try commenting out the following lines in your configuration file:
```toml
[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
```

**Comment by gry** [comment]
> You probably aren't seeing anything on the console because if you're using the `config.toml` that is supplied with the `mainnet.zip`, your config file is set to log to a file instead of the console. Try commenting out the following lines in your configuration file:
> 
> ```toml
> [Node.LogConfig]
> FilePath = "bsc.log"
> MaxBytesSize = 10485760
> Level = "info"
> FileRoot = ""
> ```

You were completely right. It is trying to connect to peers. However, I have no idea why but I continuously get errors like this one, and it does not seem to sync anything:

peer=89027a8b err="peer connected on snap without compatible eth support"

It has been like this for several hours and I do not see any kind of log message showing any progress. I also started a console with geth attach and eth.blockNumber shows 0

**Comment by mcoelho80** [comment]
I'm using a 4Tb NVME and I keep getting only 1 block per sync, age parameter is getting older and older.

Sync will never finish this way.

**Comment by Undead8** [comment]
@gry Yeah I got the same and I think it may be because you are trying a "snap" sync and no node is providing a snapshot. Try downloading the [official snapshot](https://github.com/binance-chain/bsc-snapshots) and sync from there instead.

**Comment by Undead8** [comment]
@mcoelho80 Official minimum requirements seem outdated. Do you have at least 64Gb of RAM and at least 50 peers?
