### ISSUE TITLE
msg="Aborting state snapshot generation"

### ISSUE THREAD

**Issue by tropo76** [bnb-chain/bsc-snapshots#51]
hello, 
my node is synced with 1.1.4, but it's unstable. it's loosing synchronisation every minutn then re-sync again 

i got this log:

msg="Aborting state snapshot generation"
msg="Resuming state snapshot generation"

any idea why ?

**Comment by htkcodes** [comment]
Set MaxPeers to 0 and restart GETH you should only see.. Generating state snapshot, The node will be out of sync as it will not receive any new blocks anymore.This will stop the process of receiving new blocks (so the node will be outdated), but it means the snapshot process is not interrupted anymore.

you should see sumn like this at the end msg=”Generated state snapshot” accounts=61,032,861 slots=603,991,878 storage=”47.45 GiB” elapsed=50h17m39.469s

which means its finished

now set back your maxpeers and wait for it to sync again
