### ISSUE TITLE
How to get a out-of-date snapshot?

### ISSUE THREAD

**Issue by barryz** [bnb-chain/bsc-snapshots#57]
For some purpose, we need to start Geth with a specific block height, eg. 10300101. The latest snapshot's start height may not satisfy us. Can you provide an out-of-date snapshot for us?

**Comment by barryz** [comment]
We try to run `debug.setHead()`, but cannot change the current block height.

**Comment by iakisme** [comment]
@barryz you can checkout the git commit history.

**Comment by barryz** [comment]
> @barryz you can checkout the git commit history.

403 access denied when I tried to download the history archive file.
