### ISSUE TITLE
The hard drive filled up very quickly

### ISSUE THREAD

**Issue by datacoder-io** [bnb-chain/bsc-snapshots#65]
It's been almost a month since I launched Node on my server and it works without any problems.

But I see that the hard server is filling up very fast.

After a month, the 2TB hard drive is almost full.

All data filled in /node/geth/chaindata

Is this normal? if yes, i think i must add 1T hard every month to server :/

**Comment by lobovkin** [comment]
From https://github.com/binance-chain/bsc/issues/502
> According to the test, the performance of a fullnoded will degrade when the storage size exceeds 1.5T. We suggest the fullnode always keeps light storage by pruning the storage.
> 
> Following are the steps to do prune:
> 
> Stop the BSC node first.
> Run nohup geth snapshot prune-state --datadir {the data dir of your bsc node} &. It will take 3-5 hours to finish.
> Start the node once it is done.

**Comment by miohtama** [comment]
> After a month, the 2TB hard drive is almost full.

2 TB terabytes is not enough to run Binance Smart Chain,
