### ISSUE TITLE
Can you update the snapshot every day?

### ISSUE THREAD

**Issue by ggxed** [bnb-chain/bsc-snapshots#66]
It takes a very long time to sync from outdated snapshots of the node, please upload them every day

**Comment by LuisUrrutia** [comment]
@guagualvcha @iakisme @runkolyma @DefiDebauchery

**Comment by mcoelho80** [comment]
It's almost impossible to get synced, and to make thinks worst, BSC staff doesn't upload daily snapshots here.

This is being an invite to move to Polygon and Solana.

**Comment by longb1997** [comment]
+1

**Comment by Sharp-Lee** [comment]
@iakisme

**Comment by overload-ak** [comment]
+1

**Comment by jun0tpyrc** [comment]
please update, catching up 3days data gonna take day

**Comment by iakisme** [comment]
every 3 days

**Comment by Fredoz19** [comment]
so there is a new snaposhot today ?
any ETA ?

**Comment by zigg76** [comment]
Last one was 4dayd ago. Already 1day late. :)

**Comment by allada** [comment]
I used to provide an archive snapshot that would update every day in an automated manner (but it's ~4 days behind now because I made a mistake)... For the devs maintaining this project, I can provide some pointers (if desired) on how I did it with having less than 10 seconds of downtime while the snapshot was taken and I would upload the snapshot in a new process, then delete the snapshot when finished.

**Comment by ggxed** [comment]
> I provide a free public archive snapshot that updates every day in an automated manner (but it's ~4 days behind now because I made a mistake)... For the devs maintaining this project, I can provide some pointers (if desired) on how I did it with having less than 10 seconds of downtime while the snapshot was taken and I would upload the snapshot in a new process, then delete the snapshot when finished.
@allada 
Great, could you give a link where you post snapshots?

**Comment by welnetos** [comment]
> I provide a free public archive snapshot that updates every day in an automated manner (but it's ~4 days behind now because I made a mistake)... For the devs maintaining this project, I can provide some pointers (if desired) on how I did it with having less than 10 seconds of downtime while the snapshot was taken and I would upload the snapshot in a new process, then delete the snapshot when finished.

Please man upload it:? here is taking 4 days already to sync :(

**Comment by allada** [comment]
> > I provide a free public archive snapshot that updates every day in an automated manner (but it's ~4 days behind now because I made a mistake)... For the devs maintaining this project, I can provide some pointers (if desired) on how I did it with having less than 10 seconds of downtime while the snapshot was taken and I would upload the snapshot in a new process, then delete the snapshot when finished.
> 
> Please man upload it:? here is taking 4 days already to sync :(

I decided to pause updating the current `geth` archive snapshots and focus on creating an `erigon` BSC archive snapshot. Sadly I estimate this will take around 3 weeks to finish, but should reduce the size of the snapshot to a few TB instead of a few dozen TB and much faster.

**Comment by perfectcircle2020** [comment]
@allada can you please upload also the full node version of the snapshot?

**Comment by perfectcircle2020** [comment]
@allada Thank you! 

How large is the node snapshot? Are 2TB sufficient?

**Comment by allada** [comment]
I believe uncompressed it's around 4 to 4.5TB. If you use a compressed filesystem with `lz4`, you can probably fit it onto a 2-3TB drive.

**Comment by du5** [comment]
> @allada can you please upload also the full node version of the snapshot for `erigon`?

erigon bsc database from block 15698580
flags: —prune=hrtc --chain=bsc 

https://github.com/du5/bsc-snapshots/blob/main/README.md
