### ISSUE TITLE
scheduled snapshot updates

### ISSUE THREAD

**Issue by versionCollector** [bnb-chain/bsc-snapshots#67]
Can you make a scheduled update for snapshots, please? For example, every day or every 2 days? The problem is that node sync with an ongoing snapshot (which is no longer relevant) usually takes a few days. Block sync speed is too slow at the moment

**Comment by iakisme** [comment]
every 3 days

**Comment by versionCollector** [comment]
nice, thank you

**Comment by versionCollector** [comment]
How often are you going to pull snapshots now? Why did you remove your eta for snapshots every 3 days?

**Comment by nilampatel-engineer** [comment]
if snapshot gets updated every 3 days does that means we will have to update our node every 3 days?
