### ISSUE TITLE
Use fastest compressor

### ISSUE THREAD

**Issue by voron** [bnb-chain/bsc-snapshots#69]
gzip decompression speed is slow as it's old and single-threaded. 
Could we pls replace it with f.e. `zstd` or remove compression at all, as compression ratio is really low.

**Comment by iakisme** [comment]
is it faster than pigz ?

**Comment by voron** [comment]
I've looked into [zstd](https://facebook.github.io/zstd/) and it's faster in both compression and decompression. Here is my compare with first 10GB of bsc snapshot
```
time zstd -T0 t1.tar
t1.tar               : 92.91%   (10701414400 => 9943109815 bytes, t1.tar.zst)

real    0m18,356s
user    1m25,181s
sys     0m8,386s

time pigz -k t1.tar

real    0m43,369s
user    8m3,278s
sys     0m17,067s

time zstd -T0 -dc t1.tar.zst > /dev/null

real    0m4,827s
user    0m3,877s
sys     0m0,922s

time pigz -dc t1.tar.gz > /dev/null

real    0m44,224s
user    0m52,403s
sys     0m5,368s
# file sizes 
ls -la t1*
-rw-r--r-- 1 root  root  10701414400 Dec  2 08:57 t1.tar
-rw-r--r-- 1 root  root   9923216855 Dec  2 08:57 t1.tar.gz
-rw-r--r-- 1 root  root   9943109815 Dec  2 09:31 t1.tar.zst
```
I'm sure it's possible to get smaller file size with non-default compression level while keeping decompression speed fast enough.   But I don't think it's required. 

The goal is to minimise round-trip - "compress->upload->download->decompress" **time**, taking into account that download & decompress happens much more frequently then compress & upload.

With `pigz` and current BSC archive we're stuck with 130-170MB/s decompression speed, while zstd boosts it to 2GB/s + with ~the same archive size

**Comment by voron** [comment]
@iakisme 
>is it faster than pigz ?

I've just picked a bigger part of BSC snapshot than previous time, first 160GB, and here are my compression results
```
time zstd -T0 geth-20211130.tar
geth-20211130.tar    : 76.35%   (162239381504 => 123867769428 bytes, geth-20211130.tar.zst)

real    11m3,995s
user    19m50,338s
sys     2m3,168s

time pigz -k geth-20211130.tar

real    16m43,312s
user    116m28,066s
sys     3m44,644s

 -rw-r--r--  1 root  root  162239381504 Dec  2 11:06 geth-20211130.tar
-rw-r--r--  1 voron users 123867769428 Dec  2 17:47 geth-20211130.tar.zst
-rw-r--r--  1 voron users 134205251696 Dec  2 11:06 geth-20211130.tar.gz

```
Thus I can say that zstd compresses fist 160GB of bsc snapshot 1.5x faster in my case (disk-bound, both src and dst are the same consumer single NVME), consumes 6 times less CPU and produces ~6.3% smaller file.

**Comment by iakisme** [comment]
cool, let me try, thanks.

**Comment by allada** [comment]
If you end up going with `zstd`, I highly suggest spending the time to run a very high compression before uploading (maybe `-15` or even more)... It has minimal impact on decompression speed and I've seen double digit better compression reduction.

I have also had even higher compression ratios with `--long=31`, however, setting this flag forces the user (during decompression) to add the same flag or it won't work (but it will tell you if you forget).

**Comment by iakisme** [comment]
@voron  i think lz4 is more faster at uncompression, can you try the latest snapshot?

**Comment by allada** [comment]
> @voron i think lz4 is more faster at uncompression, can you try the latest snapshot?

lz4 is very fast at compression and decompression, but doesn't provide very good decompression ratios. zstd is also very fast... not as fast as lz4, but still one of the fastest and provides very good compression ratios.

I savvy user could do something like:
```
curl -o - https://tf-dex-prod-public-snapshot-site1.s3-accelerate.amazonaws.com/link-to-file | zstd -d | tar xf -
```
If the user really cares about doing it fast. Download speed is almost certainly slower than decompression speed.

**Comment by iakisme** [comment]
Yes, but i think decompression ratios is not the important things. Because it's hard to compression snapshot under 700GB, and you will spend a lot of time to uncompression.

**Comment by voron** [comment]
@iakisme 
In my tests with latest snapshot `geth-20211220.tar` lz4 compression ratio is low, but decompression speed is the best one
```
-rw-r--r-- 1 root root 960G Dec 20 11:50 geth-20211220.tar
-rw-r--r-- 1 root root 913G Dec 20 11:50 geth-20211220.tar.lz4
-rw-r--r-- 1 root root 786G Dec 24 15:24 geth-20211220.tar.zst
```
lz4 decompression - 1155MB/s,  compression ratio 1.05
```
# mbuffer -m3% -i geth-20211220.tar.lz4 | time lz4 -d  > /dev/null
in @  0.0 kiB/s, out @ 1167 MiB/s,  912 GiB total, buffer   4% full, 100% done
summary:  912 GiByte in 13min 28.7sec - average of 1155 MiB/s
424.12user 358.40system 13:28.71elapsed 96%CPU (0avgtext+0avgdata 9808maxresident)k
16inputs+0outputs (1major+2147minor)pagefaults 0swaps
```
zstd decompression - 766MB/s, compression ratio 1.22
```
# mbuffer -m3% -i geth-20211220.tar.zst | time zstd -d  > /dev/null
in @  0.0 kiB/s, out @  975 MiB/s,  786 GiB total, buffer   1% full, 100% donee
summary:  786 GiByte in 17min 30.3sec - average of  766 MiB/s
723.85user 190.10system 17:30.31elapsed 87%CPU (0avgtext+0avgdata 4584maxresident)k
1696inputs+0outputs (5major+741minor)pagefaults 0swaps
```
zstd compress time just in case someone cares
```
# time zstd -3 -T0 geth-20211220.tar -o geth-20211220.tar.zst
geth-20211220.tar    : 81.93%   (1029983098880 => 843854969252 bytes, geth-20211220.tar.zst)

real    50m1,945s
user    302m42,760s
sys     22m0,847s
```
tar decompression with disk writing - around 1100MB/s in my tests, thus there is no need to outperform this value. 

As long as [single-threaded] network download or source disk are capable to provide stable 1000MB/s ( or 8Gbit/s )  - there is a point to use `lz4`.   With lower network/disk speed it may be better to use `zstd`. 
<hr>

Anyway `lz4` is much better than gzip, huge thanks.

**Comment by allada** [comment]
S3 almost always is the bottleneck at ~250-300/Mbs for upload or download
unless you perform a lot of crazy tricks. You can pipe a tar + compressor +
S2 upload all at the same time, so the slowest of the 3 is the true
bottleneck (and the same on download).
