### ISSUE TITLE
snapshot link

### ISSUE THREAD

**Issue by nilampatel-engineer** [bnb-chain/bsc-snapshots#85]
There are two snapshot link2 and link3 provided, just wanted to know what is the diff in between them?

**Comment by dgdeivid** [comment]
Asia region, US or EU.

**Comment by nilampatel-engineer** [comment]
Thank you dgdeivid, I understand that but which link is for EU region? or this link directs to all the region?

**Comment by zigg76** [comment]
bro, there is 3 link. each one for a region...

**Comment by dgdeivid** [comment]
> Thank you dgdeivid, I understand that but which link is for EU region? or this link directs to all the region?

"EU Endpoint" link is for EU region

**Comment by nilampatel-engineer** [comment]
and what about hose 2 links given in metadata


https://github.com/binance-chain/bsc-snapshots/blob/main/metadata/geth-download-link2
and
https://github.com/binance-chain/bsc-snapshots/blob/main/metadata/geth-download-link3

**Comment by iakisme** [comment]
BTW, do you think it's still necessary to provide download link as file ?  Is it help when you want to integrate with your pipeline ? i will remove these file for now.
