### ISSUE TITLE
Cannot unzip the snapshot with tar -I lz4 zxvf geth.tar.lz4 command

### ISSUE THREAD

**Issue by ai323** [bnb-chain/bsc-snapshots#88]
Cannot unzip the snapshot with tar -I lz4 zxvf geth.tar.lz4 command, it gives me following error:
`tar: You must specify one of the '-Acdtrux', '--delete' or '--test-label' options
Try 'tar --help' or 'tar --usage' for more information.`

**Comment by iakisme** [comment]
sorry, can you try: tar -I lz4 xvf geth.tar.lz4 ?

**Comment by Sakiya999** [comment]
I tried the command: tar -I lz4 -xvf geth.tar.lz4
it‘s the following error:
> Error 44 : Unrecognized header : file cannot be decoded
tar: Child returned status 44
tar: Error is not recoverable: exiting now

**Comment by angryb888** [comment]
I encountered the same problem when decompressing, when I used tar -I lz4 xvf geth.tar.lz4 to execute, the result did not change, or
tar: You must specify one of the `-Acdtrux' or `--test-label' options
Try `tar --help' or `tar --usage' for more information.

**Comment by frankmartin2** [comment]
I encountered the same problem when decompressing, when I used tar -I lz4 xvf geth.tar.lz4 to execute, the result did not change, or
tar: You must specify one of the -Acdtrux' or --test-label' options
Try tar --help' or tar --usage' for more information.

**Comment by nitika14699** [comment]
use this command to unzip file:   lz4 -d dir.tar.lz4 | tar -xv

**Comment by nitika14699** [comment]
> use this command to unzip file: lz4 -d dir.tar.lz4 | tar -xv

this will definitely help

**Comment by nitika14699** [comment]
> sorry, can you try: tar -I lz4 xvf geth.tar.lz4 ?

this command is also not working

**Comment by mliang-circle** [comment]
```
apt-get install -y lz4
tar -I lz4 -xvf geth.tar.lz4
```
