### ISSUE TITLE
solution to unzip geth.tar.lz4

### ISSUE THREAD

**Issue by nitz9922** [bnb-chain/bsc-snapshots#89]
( tar -I lz4 zxvf geth.tar.lz4 ) this command is not working to unzip file.
so use this command to unzip file: lz4 -d dir.tar.lz4 | tar -xv

**Comment by zigg76** [comment]
yep, z and lz4 are a double command.

**Comment by AdminAnticaptcha** [comment]
I tried to install everything related to lz4 and it worked

apt install liblz4-1 libcompress-lz4-perl liblz4-1-dbg liblz4-dev liblz4-tool libroslz4-1d libroslz4-dev
