### ISSUE TITLE
unzip while downloading not working

### ISSUE THREAD

**Issue by contessanicola** [bnb-chain/bsc-snapshots#94]
wget -q -O - snapshot URL | tar -I lz4 -xvf -

This command is not working for me, it starts and exits immediately, I read that you should use use lz4 -d dir.tar.lz4 | tar -xv to unzip the file (but if i replace the right part with that it returns an error).
I would like to do it while downloading since I don't have enough space

wget -q -O - snapshot URL | tar -I lz4 -xvf -
wget -q -O - snapshot URL | lz4 -d dir.tar.lz4 | tar -xv 

neither seem to work.

**Comment by contessanicola** [comment]
I used this command and it seems to work, I'll update once it has finished

wget -O - "URL" | lz4 -d - | tar -xv

**Comment by kugimiya530** [comment]
> 

really appreciate i find the soultion very long time

**Comment by BrokedTV** [comment]
Is there a way to uncompress while downloading with aria2c?

**Comment by ZRory** [comment]
thanks，i think the owner shoud update readme file
