### ISSUE TITLE
total size of the file after extracting is ? 

### ISSUE THREAD

**Issue by sunset1234321** [bnb-chain/bsc-snapshots#96]
I have bought a 2TB 980pro nvme ssd.

Seems after unzip,  __the size is more than 2tb?__

I am planning to buy a 4tb nvme ssd,   is 4tb enough???????        

Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by bencao** [comment]
Likely not, current bsc full node I have uses 6T storage..

**Comment by sunset1234321** [comment]
> Likely not, current bsc full node I have uses 6T storage..

@bencao may i know what storage device are u using?  6TB of nvme SSD is extremely expensive

**Comment by 0fuz** [comment]
@sunset1234321 current unzipped snap data consume ~1.5-1.6tb (after full sync). 2tb volume will be enough max 6months I think

**Comment by sunset1234321** [comment]
@0fuz  thanks   one of the commenters says it used 6T storage,  it freaked me out

**Comment by algobotishere** [comment]
Don't worry, it depends on your sync style. Mine is 3.5 TB fully synced

**Comment by 0fuz** [comment]
@sunset1234321 3d ago I used fresh snapshot and then full sync. After that 1.1tb used. I think other data become old and could be pruned by state-prune utility
